using System;
using System.Collections.Generic;

namespace IndustrialDataCollection.Utils
{
    /// <summary>
    /// Industrial ChineseEnglish vocabulary for semantic tag auto-generation (v1.10.0: 2588+ terms, compound decomposition)
    /// </summary>
    public static class IndustrialVocabulary
    {
        private static readonly Dictionary<string, string> Map = new Dictionary<string, string>
        {
            {"工厂", "plant"}, {"车间", "shopfloor"}, {"产线", "line"}, {"工段", "section"}, 
            {"工位", "station"}, {"挤压机", "extruder"}, {"注塑机", "injection_molding"}, {"冲压机", "press"}, 
            {"折弯机", "bending_machine"}, {"切割机", "cutter"}, {"焊接机", "welder"}, {"磨床", "grinder"}, 
            {"铣床", "milling"}, {"车床", "lathe"}, {"钻床", "drill"}, {"加工中心", "cnc"}, 
            {"机器人", "robot"}, {"传送带", "conveyor"}, {"包装机", "packaging"}, {"灌装机", "filling_machine"}, 
            {"贴标机", "labeler"}, {"打码机", "coder"}, {"封口机", "sealer"}, {"灭菌机", "sterilizer"}, 
            {"混合机", "mixer"}, {"搅拌机", "agitator"}, {"粉碎机", "crusher"}, {"筛分机", "screener"}, 
            {"干燥机", "dryer"}, {"冷却塔", "cooling_tower"}, {"压缩机", "compressor"}, {"泵", "pump"}, 
            {"风机", "fan"}, {"电机", "motor"}, {"锅炉", "boiler"}, {"热交换器", "heat_exchanger"}, 
            {"反应釜", "reactor"}, {"蒸馏塔", "distillation_column"}, {"离心机", "centrifuge"}, {"温度", "temperature"}, 
            {"压力", "pressure"}, {"流量", "flow_rate"}, {"速度", "speed"}, {"转速", "rpm"}, 
            {"扭矩", "torque"}, {"功率", "power"}, {"电流", "current"}, {"电压", "voltage"}, 
            {"电阻", "resistance"}, {"频率", "frequency"}, {"能耗", "energy"}, {"位移", "displacement"}, 
            {"位置", "position"}, {"角度", "angle"}, {"振动", "vibration"}, {"噪声", "noise"}, 
            {"重量", "weight"}, {"密度", "density"}, {"粘度", "viscosity"}, {"浓度", "concentration"}, 
            {"ph值", "ph"}, {"电导率", "conductivity"}, {"湿度", "humidity"}, {"露点", "dew_point"}, 
            {"氧含量", "oxygen"}, {"液位", "level"}, {"料位", "material_level"}, {"开关", "switch"}, 
            {"状态", "status"}, {"运行", "running"}, {"故障", "fault"}, {"报警", "alarm"}, 
            {"产量", "output"}, {"计数", "count"}, {"时长", "duration"}, {"周期", "cycle"}, 
            {"进料", "feed"}, {"出料", "discharge"}, {"回料", "return"}, {"加热", "heating"}, 
            {"冷却", "cooling"}, {"干燥", "drying"}, {"混合", "mixing"}, {"搅拌", "stirring"}, 
            {"粉碎", "crushing"}, {"筛分", "screening"}, {"过滤", "filtration"}, {"蒸馏", "distillation"}, 
            {"萃取", "extraction"}, {"反应", "reaction"}, {"发酵", "fermentation"}, {"灭菌", "sterilization"}, 
            {"灌装", "filling"}, {"封口", "sealing"}, {"贴标", "labeling"}, {"包装", "packing"}, 
            {"清洗", "cleaning"}, {"消毒", "disinfection"}, {"预热", "preheating"}, {"保温", "insulation"}, 
            {"加压", "pressurization"}, {"减压", "depressurization"}, {"排空", "venting"}, {"进", "in"}, 
            {"出", "out"}, {"入口", "inlet"}, {"出口", "outlet"}, {"合格", "qualified"}, 
            {"不合格", "rejected"}, {"良品", "good"}, {"次品", "defect"}, {"废品", "scrap"}, 
            {"返工", "rework"}, {"首检", "first_inspection"}, {"巡检", "patrol_inspection"}, {"末检", "final_inspection"}, 
            {"尺寸", "dimension"}, {"公差", "tolerance"}, {"硬度", "hardness"}, {"粗糙度", "roughness"}, 
            {"外观", "appearance"}, {"色差", "color_diff"}, {"螺杆", "screw"}, {"料筒", "barrel"}, 
            {"模具", "mold"}, {"喷嘴", "nozzle"}, {"阀门", "valve"}, {"管道", "pipe"}, 
            {"法兰", "flange"}, {"轴承", "bearing"}, {"齿轮", "gear"}, {"皮带", "belt"}, 
            {"链条", "chain"}, {"导轨", "rail"}, {"气缸", "cylinder"}, {"液压", "hydraulic"}, 
            {"气动", "pneumatic"}, {"传感器", "sensor"}, {"执行器", "actuator"}, {"控制器", "controller"}, 
            {"变频器", "vfd"}, {"伺服", "servo"}, {"步进", "stepper"}, {"继电器", "relay"}, 
            {"接触器", "contactor"}, {"断路器", "breaker"}, {"熔断器", "fuse"}, {"变压器", "transformer"}, 
            {"开关电源", "power_supply"}, {"油泵", "oil_pump"}, {"水泵", "water_pump"}, {"真空泵", "vacuum_pump"}, 
            {"水", "water"}, {"油", "oil"}, {"气", "gas"}, {"蒸汽", "steam"}, 
            {"原料", "raw_material"}, {"成品", "finished_product"}, {"半成品", "semi_finished"}, {"粉末", "powder"}, 
            {"颗粒", "granule"}, {"液体", "liquid"}, {"气体", "gas"}, {"固体", "solid"}, 
            {"浆料", "slurry"}, {"添加剂", "additive"}, {"催化剂", "catalyst"}, {"空调", "hvac"}, 
            {"通风", "ventilation"}, {"照明", "lighting"}, {"给水", "water_supply"}, {"排水", "drainage"}, 
            {"废水", "wastewater"}, {"废气", "exhaust_gas"}, {"废渣", "waste_residue"}, {"配电", "power_distribution"}, 
            {"供气", "gas_supply"}, {"压缩空气", "compressed_air"}, {"氮气", "nitrogen"}, {"氧气", "oxygen_gas"}, 
            {"号", "no"}, {"组", "group"}, {"套", "set"}, {"台", "unit"}, 
            {"郑州", "zhengzhou"}, {"北京", "beijing"}, {"上海", "shanghai"}, {"广州", "guangzhou"}, 
            {"深圳", "shenzhen"}, {"苏州", "suzhou"}, {"杭州", "hangzhou"}, {"成都", "chengdu"}, 
            {"武汉", "wuhan"}, {"重庆", "chongqing"}, {"天津", "tianjin"}, {"南京", "nanjing"}, 
            {"东莞", "dongguan"}, {"佛山", "foshan"}, {"青岛", "qingdao"}, {"沈阳", "shenyang"}, 
            {"西安", "xian"}, {"长沙", "changsha"}, {"PLC", "plc"}, {"SCADA", "scada"}, 
            {"DCS", "dcs"}, {"HMI", "hmi"}, {"RTU", "rtu"}, {"OPC", "opc"}, 
            {"Profibus", "profibus"}, {"Modbus", "modbus"}, {"EtherCAT", "ethercat"}, {"Profinet", "profinet"}, 
            {"DeviceNet", "devicenet"}, {"CANopen", "canopen"}, {"EthernetIP", "ethernet_ip"}, {"BACnet", "bacnet"}, 
            {"LonWorks", "lonworks"}, {"Fieldbus", "fieldbus"}, {"OPCUA", "opc_ua"}, {"MQTT", "mqtt"}, 
            {"模拟量", "analog"}, {"数字量", "digital"}, {"离散量", "discrete"}, {"脉冲", "pulse"}, 
            {"计时器", "timer"}, {"计数器", "counter"}, {"寄存器", "register"}, {"线圈", "coil"}, 
            {"输入寄存器", "input_register"}, {"保持寄存器", "holding_register"}, {"离散输入", "discrete_input"}, {"线圈状态", "coil_status"}, 
            {"PID", "pid"}, {"比例", "proportional"}, {"积分", "integral"}, {"微分", "derivative"}, 
            {"设定值", "setpoint"}, {"过程值", "process_value"}, {"偏差", "deviation"}, {"输出值", "output_value"}, 
            {"前馈", "feedforward"}, {"串级", "cascade"}, {"比值", "ratio"}, {"分程", "split_range"}, 
            {"超驰", "override"}, {"自整定", "auto_tuning"}, {"手动", "manual"}, {"自动", "automatic"}, 
            {"远程", "remote"}, {"就地", "local"}, {"联锁", "interlock"}, {"互锁", "mutual_lock"}, 
            {"旁路", "bypass"}, {"紧急停机", "emergency_stop"}, {"联锁停机", "interlock_stop"}, {"铝", "aluminum"}, 
            {"铜", "copper"}, {"钢", "steel"}, {"铁", "iron"}, {"钛", "titanium"}, 
            {"镁", "magnesium"}, {"锌", "zinc"}, {"镍", "nickel"}, {"合金", "alloy"}, 
            {"型材", "profile"}, {"板材", "plate"}, {"棒材", "bar"}, {"管材", "tube"}, 
            {"线材", "wire"}, {"铝棒", "aluminum_bar"}, {"铝型材", "aluminum_profile"}, {"锭", "ingot"}, 
            {"坯料", "billet"}, {"铸锭", "cast_ingot"}, {"铝液", "molten_aluminum"}, {"熔炼", "smelting"}, 
            {"铸造", "casting"}, {"连铸", "continuous_casting"}, {"轧制", "rolling"}, {"锻造", "forging"}, 
            {"冲压", "stamping"}, {"拉伸", "stretching"}, {"弯曲", "bending"}, {"矫直", "straightening"}, 
            {"切割", "cutting"}, {"锯切", "sawing"}, {"矫平", "leveling"}, {"探伤", "ndt"}, 
            {"退火", "annealing"}, {"淬火", "quenching"}, {"回火", "tempering"}, {"时效", "aging"}, 
            {"均匀化", "homogenization"}, {"固溶", "solution_treatment"}, {"时效处理", "aging_treatment"}, {"挤压比", "extrusion_ratio"}, 
            {"挤压速度", "extrusion_speed"}, {"挤出量", "extrusion_output"}, {"模具温度", "mold_temperature"}, {"料筒温度", "barrel_temperature"}, 
            {"前梁", "front_beam"}, {"主缸", "main_cylinder"}, {"锁模力", "clamping_force"}, {"顶出", "ejection"}, 
            {"牵引", "puller"}, {"中断锯", "cutoff_saw"}, {"石化", "petrochemical"}, {"炼油", "oil_refining"}, 
            {"乙烯", "ethylene"}, {"丙烯", "propylene"}, {"丁二烯", "butadiene"}, {"苯", "benzene"}, 
            {"甲苯", "toluene"}, {"二甲苯", "xylene"}, {"裂解", "cracking"}, {"重整", "reforming"}, 
            {"加氢", "hydrogenation"}, {"脱硫", "desulfurization"}, {"脱氮", "denitrification"}, {"焦化", "coking"}, 
            {"催化", "catalysis"}, {"裂化", "cracking_unit"}, {"聚合", "polymerization"}, {"聚丙烯", "polypropylene"}, 
            {"聚乙烯", "polyethylene"}, {"聚氯乙烯", "pvc"}, {"聚酯", "polyester"}, {"合成", "synthesis"}, 
            {"芳烃", "aromatics"}, {"烯烃", "olefin"}, {"烷烃", "alkane"}, {"石脑油", "naphtha"}, 
            {"原油", "crude_oil"}, {"柴油", "diesel"}, {"汽油", "gasoline"}, {"煤油", "kerosene"}, 
            {"润滑油", "lubricant"}, {"沥青", "asphalt"}, {"蜡油", "wax_oil"}, {"减压渣油", "vacuum_residue"}, 
            {"发电", "power_generation"}, {"火电", "thermal_power"}, {"水电", "hydropower"}, {"核电", "nuclear_power"}, 
            {"风电", "wind_power"}, {"光伏", "photovoltaic"}, {"太阳能", "solar"}, {"储能", "energy_storage"}, 
            {"充电", "charging"}, {"放电", "discharging"}, {"并网", "grid_connected"}, {"离网", "off_grid"}, 
            {"升压站", "step_up_station"}, {"降压站", "step_down_station"}, {"变电站", "substation"}, {"开关站", "switch_station"}, 
            {"配电房", "distribution_room"}, {"隔离开关", "disconnector"}, {"互感器", "transformer_pt"}, {"避雷器", "arrester"}, 
            {"母线", "busbar"}, {"电缆", "cable"}, {"架空线", "overhead_line"}, {"无功补偿", "reactive_compensation"}, 
            {"有功", "active_power"}, {"无功", "reactive_power"}, {"视在功率", "apparent_power"}, {"功率因数", "power_factor"}, 
            {"谐波", "harmonic"}, {"闪变", "flicker"}, {"电压暂降", "voltage_sag"}, {"频率偏差", "frequency_deviation"}, 
            {"相序", "phase_sequence"}, {"三相不平衡", "three_phase_unbalance"}, {"接地", "grounding"}, {"绝缘", "insulation_test"}, 
            {"耐压", "withstand_voltage"}, {"局放", "partial_discharge"}, {"净水", "clean_water"}, {"污水", "sewage"}, 
            {"中水", "reclaimed_water"}, {"再生水", "recycled_water"}, {"污泥", "sludge"}, {"沉淀", "sedimentation"}, 
            {"混凝", "coagulation"}, {"絮凝", "flocculation"}, {"气浮", "air_flotation"}, {"曝气", "aeration"}, 
            {"生化", "biochemical"}, {"好氧", "aerobic"}, {"厌氧", "anaerobic"}, {"缺氧", "anoxic"}, 
            {"硝化", "nitrification"}, {"MBR", "mbr"}, {"RO", "ro"}, {"反渗透", "reverse_osmosis"}, 
            {"超滤", "ultrafiltration"}, {"纳滤", "nanofiltration"}, {"微滤", "microfiltration"}, {"EDI", "edi"}, 
            {"离子交换", "ion_exchange"}, {"活性炭", "activated_carbon"}, {"砂滤", "sand_filter"}, {"炭滤", "carbon_filter"}, 
            {"臭氧", "ozone"}, {"紫外", "uv"}, {"加氯", "chlorination"}, {"消毒剂", "disinfectant"}, 
            {"余氯", "residual_chlorine"}, {"浊度", "turbidity"}, {"色度", "chromaticity"}, {"COD", "cod"}, 
            {"BOD", "bod"}, {"TOC", "toc"}, {"TDS", "tds"}, {"SS", "ss"}, 
            {"氨氮", "ammonia_nitrogen"}, {"总氮", "total_nitrogen"}, {"总磷", "total_phosphorus"}, {"溶解氧", "dissolved_oxygen"}, 
            {"ORP", "orp"}, {"食品", "food"}, {"饮料", "beverage"}, {"乳品", "dairy"}, 
            {"啤酒", "beer"}, {"白酒", "liquor"}, {"酿酒", "brewing"}, {"调酒", "blending"}, 
            {"巴氏", "pasteurization"}, {"杀菌", "sterilization"}, {"UHT", "uht"}, {"均质", "homogenizer"}, 
            {"脱气", "degassing"}, {"浓缩", "concentration"}, {"蒸发", "evaporation"}, {"结晶", "crystallization"}, 
            {"喷雾干燥", "spray_drying"}, {"冷冻干燥", "freeze_drying"}, {"造粒", "granulation"}, {"包衣", "coating"}, 
            {"压片", "tabletting"}, {"胶囊填充", "capsule_filling"}, {"糖衣", "sugar_coating"}, {"发酵罐", "fermenter"}, 
            {"种子罐", "seed_tank"}, {"补料", "feed_addition"}, {"消泡", "defoaming"}, {"取样", "sampling"}, 
            {"CIP", "cip"}, {"SIP", "sip"}, {"清洗液", "cleaning_solution"}, {"消毒液", "disinfectant_solution"}, 
            {"冲洗", "rinsing"}, {"预冲洗", "pre_rinse"}, {"碱洗", "alkaline_wash"}, {"酸洗", "acid_wash"}, 
            {"热水消毒", "hot_water_disinfection"}, {"药品", "drug"}, {"原料药", "api"}, {"制剂", "formulation"}, 
            {"片剂", "tablet"}, {"胶囊", "capsule"}, {"注射剂", "injection"}, {"冻干", "lyophilization"}, 
            {"粉针", "powder_injection"}, {"口服液", "oral_liquid"}, {"软胶囊", "softgel"}, {"颗粒剂", "granules"}, 
            {"洁净室", "cleanroom"}, {"层流", "laminar_flow"}, {"隔离器", "isolator"}, {"RABS", "rabs"}, 
            {"灌装线", "filling_line"}, {"灯检", "inspection_light"}, {"装盒", "cartoning"}, {"裹包", "wrapping"}, 
            {"码垛", "palletizing"}, {"AGV", "agv"}, {"仓储", "warehouse"}, {"阴凉库", "cool_storage"}, 
            {"冷库", "cold_storage"}, {"恒温恒湿", "constant_temp_humidity"}, {"在线粒子", "online_particle"}, {"浮游菌", "airborne_bacteria"}, 
            {"沉降菌", "settling_bacteria"}, {"表面微生物", "surface_microbe"}, {"压差", "differential_pressure"}, {"换气次数", "air_change_rate"}, 
            {"温湿度", "temp_humidity"}, {"验证", "validation"}, {"确认", "qualification"}, {"水泥", "cement"}, 
            {"生料", "raw_meal"}, {"熟料", "clinker"}, {"矿渣", "slag"}, {"粉煤灰", "fly_ash"}, 
            {"石膏", "gypsum"}, {"石灰石", "limestone"}, {"黏土", "clay"}, {"铁粉", "iron_powder"}, 
            {"砂岩", "sandstone"}, {"原料磨", "raw_mill"}, {"水泥磨", "cement_mill"}, {"煤磨", "coal_mill"}, 
            {"回转窑", "rotary_kiln"}, {"预热器", "preheater"}, {"分解炉", "calciner"}, {"篦冷机", "grate_cooler"}, 
            {"选粉机", "classifier"}, {"辊压机", "roller_press"}, {"立磨", "vertical_mill"}, {"球磨", "ball_mill"}, 
            {"料仓", "silo"}, {"均化库", "homogenizing_silo"}, {"储存库", "storage_silo"}, {"散装", "bulk"}, 
            {"袋装", "bagged"}, {"纺织", "textile"}, {"纺纱", "spinning"}, {"织造", "weaving"}, 
            {"染整", "dyeing_finishing"}, {"印花", "printing"}, {"前处理", "pretreatment"}, {"退浆", "desizing"}, 
            {"煮练", "scouring"}, {"漂白", "bleaching"}, {"丝光", "mercerizing"}, {"染色", "dyeing"}, 
            {"后整理", "finishing"}, {"拉幅", "stenter"}, {"定型", "heat_setting"}, {"预缩", "preshrinking"}, 
            {"起绒", "napping"}, {"磨毛", "sanding"}, {"轧光", "calendering"}, {"涂层", "coating"}, 
            {"复合", "laminating"}, {"梳棉", "carding"}, {"并条", "drawing"}, {"粗纱", "roving"}, 
            {"细纱", "ring_spinning"}, {"络筒", "winding"}, {"整经", "warping"}, {"浆纱", "sizing"}, 
            {"穿综", "drawing_in"}, {"织布", "weaving"}, {"验布", "fabric_inspection"}, {"码布", "fabric_plaiting"}, 
            {"打包", "baling"}, {"缩水率", "shrinkage"}, {"克重", "grammage"}, {"断裂强力", "breaking_strength"}, 
            {"撕破强力", "tear_strength"}, {"汽车", "automotive"}, {"冲压车间", "stamping_shop"}, {"焊装车间", "welding_shop"}, 
            {"涂装车间", "painting_shop"}, {"总装车间", "assembly_shop"}, {"发动机", "engine"}, {"变速箱", "transmission"}, 
            {"底盘", "chassis"}, {"车身", "body"}, {"内饰", "interior"}, {"外饰", "exterior"}, 
            {"涂装", "painting"}, {"底漆", "primer"}, {"面漆", "topcoat"}, {"中涂", "midcoat"}, 
            {"清漆", "clear_coat"}, {"烘干", "baking"}, {"电泳", "electrophoresis"}, {"喷涂", "spraying"}, 
            {"机器人喷涂", "robot_spraying"}, {"拧紧", "tightening"}, {"压装", "press_fit"}, {"试漏", "leak_test"}, 
            {"在线检测", "online_testing"}, {"下线检测", "end_of_line_test"}, {"EOL", "eol"}, {"四轮定位", "wheel_alignment"}, 
            {"转毂", "roller_test"}, {"淋雨", "rain_test"}, {"路试", "road_test"}, {"电子", "electronics"}, 
            {"半导体", "semiconductor"}, {"芯片", "chip"}, {"晶圆", "wafer"}, {"光刻", "lithography"}, 
            {"刻蚀", "etching"}, {"沉积", "deposition"}, {"离子注入", "ion_implantation"}, {"CMP", "cmp"}, 
            {"扩散", "diffusion"}, {"薄膜", "thin_film"}, {"背面减薄", "backgrinding"}, {"划片", "dicing"}, 
            {"键合", "bonding"}, {"塑封", "molding"}, {"测试", "testing"}, {"分选", "sorting"}, 
            {"编带", "taping"}, {"炉管", "furnace_tube"}, {"湿法", "wet_process"}, {"干法", "dry_process"}, 
            {"洁净度", "cleanliness"}, {"百级", "class_100"}, {"千级", "class_1000"}, {"万级", "class_10000"}, 
            {"去离子水", "deionized_water"}, {"超纯水", "ultrapure_water"}, {"化学品", "chemical"}, {"特气", "special_gas"}, 
            {"大宗气体", "bulk_gas"}, {"物流", "logistics"}, {"入库", "inbound"}, {"出库", "outbound"}, 
            {"移库", "transfer"}, {"盘点", "inventory_check"}, {"拣选", "picking"}, {"分拣", "sorting"}, 
            {"WMS", "wms"}, {"WCS", "wcs"}, {"堆垛机", "stacker"}, {"穿梭车", "shuttle"}, 
            {"提升机", "elevator"}, {"输送线", "conveyor_line"}, {"滚筒线", "roller_conveyor"}, {"皮带线", "belt_conveyor"}, 
            {"链板线", "chain_conveyor"}, {"分拣口", "sorting_chute"}, {"码垛机器人", "palletizing_robot"}, {"拆垛", "depalletizing"}, 
            {"托盘", "pallet"}, {"货架", "rack"}, {"立体库", "asrs"}, {"平面库", "flat_warehouse"}, 
            {"暂存区", "buffer_zone"}, {"流量计", "flowmeter"}, {"温度计", "thermometer"}, {"压力表", "pressure_gauge"}, 
            {"液位计", "level_gauge"}, {"料位计", "level_sensor"}, {"密度计", "densimeter"}, {"浓度计", "concentration_meter"}, 
            {"粘度计", "viscometer"}, {"pH计", "ph_meter"}, {"电导率仪", "conductivity_meter"}, {"溶氧仪", "do_meter"}, 
            {"浊度计", "turbidimeter"}, {"色度计", "colorimeter"}, {"色谱仪", "chromatograph"}, {"质谱仪", "mass_spectrometer"}, 
            {"光谱仪", "spectrometer"}, {"红外", "infrared"}, {"荧光", "fluorescence"}, {"X射线", "x_ray"}, 
            {"超声波", "ultrasonic"}, {"雷达", "radar"}, {"激光", "laser"}, {"微波", "microwave"}, 
            {"称重", "weighing"}, {"检重", "checkweigher"}, {"金属检测", "metal_detector"}, {"X光异物检测", "x_ray_inspection"}, 
            {"启动", "start"}, {"停止", "stop"}, {"暂停", "pause"}, {"复位", "reset"}, 
            {"急停", "emergency_stop"}, {"待机", "standby"}, {"降温", "cooling_down"}, {"升压", "pressure_up"}, 
            {"泄压", "pressure_relief"}, {"充填", "filling"}, {"注射", "injection"}, {"保压", "holding_pressure"}, 
            {"开模", "mold_open"}, {"合模", "mold_close"}, {"抽芯", "core_pull"}, {"吹气", "air_blow"}, 
            {"抽真空", "vacuum"}, {"破真空", "vacuum_break"}, {"排料", "discharge"}, {"接料", "receive_material"}, 
            {"送料", "feed_material"}, {"循环", "cycle"}, {"单步", "single_step"}, {"联动", "linked"}, 
            {"点动", "jog"}, {"寸动", "inching"}, {"回原点", "homing"}, {"找原点", "seek_home"}, 
            {"正转", "forward"}, {"反转", "reverse"}, {"高速", "high_speed"}, {"低速", "low_speed"}, 
            {"爬行", "creep"}, {"寸进", "inching_forward"}, {"定长", "fixed_length"}, {"定重", "fixed_weight"}, 
            {"定量", "fixed_quantity"}, {"定位", "positioning"}, {"班组", "team"}, {"班次", "shift"}, 
            {"白班", "day_shift"}, {"夜班", "night_shift"}, {"早班", "morning_shift"}, {"中班", "afternoon_shift"}, 
            {"换班", "shift_change"}, {"交接班", "handover"}, {"良品率", "yield_rate"}, {"合格率", "qualification_rate"}, 
            {"废品率", "scrap_rate"}, {"稼动率", "utilization_rate"}, {"OEE", "oee"}, {"设备综合效率", "oee_full"}, 
            {"MTBF", "mtbf"}, {"MTTR", "mttr"}, {"停机", "downtime"}, {"故障停机", "fault_downtime"}, 
            {"待料停机", "material_wait_downtime"}, {"计划停机", "planned_downtime"}, {"非计划停机", "unplanned_downtime"}, {"维修", "maintenance"}, 
            {"保养", "service"}, {"点检", "checkpoint_inspection"}, {"润滑", "lubrication"}, {"紧固", "tightening"}, 
            {"清扫", "cleaning"}, {"调整", "adjustment"}, {"更换", "replacement"}, {"大修", "overhaul"}, 
            {"中修", "medium_repair"}, {"小修", "minor_repair"}, {"预防性维护", "preventive_maintenance"}, {"预测性维护", "predictive_maintenance"}, 
            {"备件", "spare_part"}, {"易损件", "wearing_part"}, {"工装", "tooling"}, {"夹具", "fixture"}, 
            {"刀具", "cutting_tool"}, {"机", "machine"}, {"号机", "machine_no"}, {"号线", "line_no"}, 
            {"线体", "line_body"}, {"设备", "equipment"}, {"装置", "apparatus"}, {"机组", "unit_set"}, 
            {"系统", "system"}, {"平台", "platform"}, {"单元", "unit"}, {"模块", "module"}, 
            {"总成", "assembly"}, {"组件", "assembly"}, {"部件", "component"}, {"零件", "part"}, 
            {"元件", "element"}, {"第一", "first"}, {"第二", "second"}, {"第三", "third"}, 
            {"第四", "fourth"}, {"第五", "fifth"}, {"前", "front"}, {"后", "rear"}, 
            {"左", "left"}, {"右", "right"}, {"上", "upper"}, {"下", "lower"}, 
            {"中", "middle"}, {"大", "large"}, {"小", "small"}, {"主", "main"}, 
            {"副", "sub"}, {"旁", "side"}, {"侧", "side"}, {"新", "new"}, 
            {"旧", "old"}, {"模拟", "simulator"}, {"数字", "digital"}, {"输入", "input"}, 
            {"输出", "output"}, {"计算", "calculation"}, {"修正", "correction"}, {"补偿", "compensation"}, 
            {"补偿值", "offset_value"}, {"修正值", "correction_value"}, {"计算值", "calculated_value"}, {"实测值", "measured_value"}, 
            {"目标值", "target_value"}, {"初始值", "initial_value"}, {"极限值", "limit_value"}, {"平均值", "average"}, 
            {"最大值", "maximum"}, {"最小值", "minimum"}, {"累计值", "accumulated"}, {"瞬时值", "instantaneous"}, 
            {"有效值", "rms_value"}, {"实验", "experiment"}, {"实际", "actual"}, {"标定", "calibration"}, 
            {"校准", "calibrate"}, {"校验", "verify"}, {"标定值", "calibration_value"}, {"测量", "measurement"}, 
            {"监测", "monitoring"}, {"监控", "monitor"}, {"控制", "control"}, {"调节", "adjust"}, 
            {"配置", "configuration"}, {"额定", "rated"}, {"标称", "nominal"}, {"标称值", "nominal_value"}, 
            {"默认", "default"}, {"参考", "reference"}, {"参考值", "reference_value"}, {"信号", "signal"}, 
            {"模拟量输入", "analog_input"}, {"模拟量输出", "analog_output"}, {"数字量输入", "digital_input"}, {"数字量输出", "digital_output"}, 
            {"脉冲输入", "pulse_input"}, {"脉冲输出", "pulse_output"}, {"开关量输入", "switch_input"}, {"开关量输出", "switch_output"}, 
            {"运行时间", "runtime"}, {"工作时间", "work_time"}, {"累计时间", "accumulated_time"}, {"等待时间", "wait_time"}, 
            {"循环时间", "cycle_time"}, {"周期时间", "period_time"}, {"延迟", "delay"}, {"延时", "delay_time"}, 
            {"超时", "timeout"}, {"物料", "material"}, {"辅料", "auxiliary_material"}, {"中间品", "intermediate"}, 
            {"原料仓", "raw_material_bin"}, {"成品仓", "product_bin"}, {"混料", "blend"}, {"配比", "ratio"}, 
            {"配方", "recipe"}, {"批次", "batch"}, {"批号", "batch_number"}, {"净重", "net_weight"}, 
            {"毛重", "gross_weight"}, {"皮重", "tare_weight"}, {"计量", "metering"}, {"给料", "feeding"}, 
            {"上料", "load"}, {"下料", "unload"}, {"碎料", "crushed_material"}, {"余料", "residual_material"}, 
            {"废料", "waste_material"}, {"正常", "normal"}, {"异常", "abnormal"}, {"运行中", "running"}, 
            {"停止中", "stopped"}, {"待机中", "standby"}, {"暂停中", "paused"}, {"维护中", "maintenance"}, 
            {"故障中", "fault"}, {"报警中", "alarm"}, {"离线", "offline"}, {"在线", "online"}, 
            {"就绪", "ready"}, {"未就绪", "not_ready"}, {"完成", "completed"}, {"进行中", "in_progress"}, 
            {"中断", "interrupted"}, {"复位中", "resetting"}, {"启动中", "starting"}, {"挤压", "extrusion"}, 
            {"挤压力", "extrusion_force"}, {"挤压温度", "extrusion_temperature"}, {"压余", "butt"}, {"残料", "remnant"}, 
            {"闷车", "stuck"}, {"拖模", "drag_mark"}, {"划伤", "scratch"}, {"擦伤", "abrasion"}, 
            {"碰伤", "dent"}, {"扭拧", "twist"}, {"弯曲度", "bend_degree"}, {"平面度", "flatness"}, 
            {"垂直度", "perpendicularity"}, {"平行度", "parallelism"}, {"圆度", "roundness"}, {"同轴度", "concentricity"}, 
            {"对称度", "symmetry"}, {"跳动", "runout"}, {"轮廓度", "profile_tolerance"}, {"位置度", "position_tolerance"}, 
            {"铝合金", "aluminum_alloy"}, {"6063", "aa6063"}, {"6061", "aa6061"}, {"6060", "aa6060"}, 
            {"6005", "aa6005"}, {"6082", "aa6082"}, {"7075", "aa7075"}, {"纯铝", "pure_aluminum"}, 
            {"铜合金", "copper_alloy"}, {"镁合金", "magnesium_alloy"}, {"钛合金", "titanium_alloy"}, {"锌合金", "zinc_alloy"}, 
            {"不锈钢", "stainless_steel"}, {"碳钢", "carbon_steel"}, {"合金钢", "alloy_steel"}, {"模具钢", "die_steel"}, 
            {"工具钢", "tool_steel"}, {"高速钢", "high_speed_steel"}, {"硬质合金", "carbide"}, {"炉温", "furnace_temperature"}, 
            {"模温", "mold_temperature"}, {"料温", "material_temperature"}, {"棒温", "billet_temperature"}, {"出口温度", "outlet_temperature"}, 
            {"入口温度", "inlet_temperature"}, {"环境温度", "ambient_temperature"}, {"设定温度", "set_temperature"}, {"实际温度", "actual_temperature"}, 
            {"温度偏差", "temperature_deviation"}, {"温差", "temperature_difference"}, {"过热", "overheat"}, {"过冷", "supercooling"}, 
            {"加热段", "heating_zone"}, {"冷却段", "cooling_zone"}, {"保温段", "holding_zone"}, {"预热段", "preheating_zone"}, 
            {"液压压力", "hydraulic_pressure"}, {"气压", "air_pressure"}, {"系统压力", "system_pressure"}, {"工作压力", "working_pressure"}, 
            {"设定压力", "set_pressure"}, {"实际压力", "actual_pressure"}, {"主缸压力", "main_cylinder_pressure"}, {"侧缸压力", "side_cylinder_pressure"}, 
            {"背压", "back_pressure"}, {"前腔压力", "front_chamber_pressure"}, {"后腔压力", "rear_chamber_pressure"}, {"锁模压力", "clamping_pressure"}, 
            {"注射压力", "injection_pressure"}, {"保压压力", "holding_pressure"}, {"充填压力", "filling_pressure"}, {"加热炉", "heating_furnace"}, 
            {"保温炉", "holding_furnace"}, {"熔炼炉", "melting_furnace"}, {"热处理炉", "heat_treatment_furnace"}, {"时效炉", "aging_furnace"}, 
            {"退火炉", "annealing_furnace"}, {"淬火炉", "quenching_furnace"}, {"回火炉", "tempering_furnace"}, {"感应炉", "induction_furnace"}, 
            {"电弧炉", "arc_furnace"}, {"电阻炉", "resistance_furnace"}, {"工频炉", "line_frequency_furnace"}, {"中频炉", "medium_frequency_furnace"}, 
            {"高频炉", "high_frequency_furnace"}, {"热剪", "hot_shear"}, {"冷剪", "cold_shear"}, {"锯床", "sawing_machine"}, 
            {"矫直机", "straightener"}, {"拉直机", "stretcher"}, {"扭拧机", "twister"}, {"矫平机", "leveler"}, 
            {"倒角机", "chamfering_machine"}, {"去毛刺机", "deburring_machine"}, {"喷砂机", "sandblasting_machine"}, {"抛光机", "polishing_machine"}, 
            {"淬火槽", "quenching_tank"}, {"水槽", "water_tank"}, {"油槽", "oil_tank"}, {"电流表", "ammeter"}, 
            {"电压表", "voltmeter"}, {"功率表", "wattmeter"}, {"电能表", "energy_meter"}, {"频率表", "frequency_meter"}, 
            {"功率因数表", "power_factor_meter"}, {"相电压", "phase_voltage"}, {"线电压", "line_voltage"}, {"相电流", "phase_current"}, 
            {"线电流", "line_current"}, {"有功功率", "active_power"}, {"无功功率", "reactive_power"}, {"总谐波", "total_harmonic"}, 
            {"电压谐波", "voltage_harmonic"}, {"电流谐波", "current_harmonic"}, {"漏电流", "leakage_current"}, {"接地电阻", "ground_resistance"}, 
            {"绝缘电阻", "insulation_resistance"}, {"绕组温度", "winding_temperature"}, {"轴承温度", "bearing_temperature"}, {"外壳温度", "housing_temperature"}, 
            {"定子", "stator"}, {"转子", "rotor"}, {"厂房", "plant_building"}, {"仓库", "warehouse"}, 
            {"办公室", "office"}, {"实验室", "laboratory"}, {"控制室", "control_room"}, {"配电室", "power_room"}, 
            {"配电间", "power_distribution_room"}, {"空压站", "compressor_station"}, {"水泵房", "pump_house"}, {"锅炉房", "boiler_room"}, 
            {"冷冻站", "refrigeration_station"}, {"空调机房", "hvac_room"}, {"消防泵房", "fire_pump_room"}, {"冷却机", "chiller"}, 
            {"变送器", "transmitter"}, {"序列号", "serial_number"}, {"零件号", "part_number"}, {"工单", "work_order"}, 
            {"停机时间", "downtime"}, {"循环次数", "cycle_count"}, {"加速度", "acceleration"}, {"力矩", "moment"}, 
            {"累计流量", "total_flow"}, {"反馈值", "feedback"}, {"上限", "upper_limit"}, {"下限", "lower_limit"}, 
            {"温度控制器", "thermostat"}, {"计时", "timing"}, {"工艺", "process"}, {"参数", "parameter"}, 
            {"工艺参数", "process_parameter"}, {"上限报警", "high_alarm"}, {"下限报警", "low_alarm"}, {"通讯", "communication"}, 
            {"连接", "connection"}, {"断开", "disconnected"}, {"已连接", "connected"}, {"警告", "warning"}, 
            {"数量", "quantity"}, {"数值", "value"}, {"读数", "reading"}, {"原始值", "raw_value"}, 
            {"工程值", "engineering_value"}, {"量程上限", "range_max"}, {"量程下限", "range_min"}, {"电流值", "current"}, 
            {"电压值", "voltage"}, {"功率值", "power"}, {"电阻值", "resistance"}, {"频率值", "frequency"}, 
            {"扭矩值", "torque"}, {"速度值", "speed"}, {"位置值", "position"}, {"压力值", "pressure"}, 
            {"温度值", "temperature"}, {"流量值", "flow_rate"}, {"液位值", "level"}, {"密度值", "density"}, 
            {"浓度值", "concentration"}, {"湿度值", "humidity"}, {"振动值", "vibration"}, {"位移值", "displacement"}, 
            {"加速度值", "acceleration"}, {"实际值", "actual_value"}, {"最大", "max"}, {"最小", "min"}, 
            {"平均", "avg"}, {"总计", "total"}, {"差值", "difference"}, {"开度", "opening"}, 
            {"关闭", "close"}, {"关闭状态", "closed"}, {"打开状态", "open"}, {"比例值", "ratio_value"}, 
            {"百分比", "percentage"}, {"增量", "increment"}, {"减量", "decrement"}, {"使能", "enable"}, 
            {"禁用", "disable"}, {"成功", "success"}, {"失败", "fail"}, {"激活", "activated"}, 
            {"未激活", "inactive"}, {"指示灯", "indicator"}, {"按钮", "button"}, {"触摸屏", "touchscreen"}, 
            {"显示屏", "display"}, {"报警器", "annunciator"}, {"蜂鸣器", "buzzer"}, {"信号灯", "signal_light"}, 
            {"门卫", "gatehouse"}, {"安全", "safety"}, {"安全门", "safety_door"}, {"安全光幕", "safety_light_curtain"}, 
            {"安全光栅", "safety_grating"}, {"安全继电器", "safety_relay"}, {"安全PLC", "safety_plc"}, {"急停按钮", "e_stop"}, 
            {"紧急停止", "emergency_stop"}, {"消防", "fire_protection"}, {"灭火", "fire_extinguishing"}, {"烟雾探测", "smoke_detection"}, 
            {"火焰探测", "flame_detection"}, {"温度探测", "temperature_detection"}, {"气体探测", "gas_detection"}, {"燃气探测", "combustible_gas_detection"}, 
            {"有毒气体", "toxic_gas"}, {"可燃气体", "combustible_gas"}, {"粉尘浓度", "dust_concentration"}, {"噪音检测", "noise_monitoring"}, 
            {"排放", "emission"}, {"废气排放", "exhaust_emission"}, {"废水排放", "wastewater_discharge"}, {"固废", "solid_waste"}, 
            {"危废", "hazardous_waste"}, {"号线体", "line_body"}, {"机台", "machine"}, {"机列", "machine_line"}, 
            {"号炉", "furnace_no"}, {"前段", "front_section"}, {"后段", "rear_section"}, {"中段", "middle_section"}, 
            {"上段", "upper_section"}, {"下段", "lower_section"}, {"左段", "left_section"}, {"右段", "right_section"}, 
            {"前区", "front_zone"}, {"后区", "rear_zone"}, {"中区", "middle_zone"}, {"上区", "upper_zone"}, 
            {"下区", "lower_zone"}, {"主线", "main_line"}, {"副线", "auxiliary_line"}, {"支线", "branch_line"}, 
            {"装配线", "assembly_line"}, {"生产线", "production_line"}, {"包装线", "packaging_line"}, {"检测线", "inspection_line"}, 
            {"浼烘湇鐢垫満", "servo_motor"}, {"鐩存祦鐢垫満", "dc_motor"}, {"鍔涚煩鐢垫満", "torque_motor"}, {"鐩寸嚎鐢垫満", "linear_motor"}, 
            {"涓昏酱鐢垫満", "spindle_motor"}, {"榻挎潯", "rack"}, {"榻胯疆榻挎潯", "rack_and_pinion"}, {"閾捐疆", "sprocket"}, 
            {"鏁版帶鏈哄簥", "cnc_machine"}, {"鐢电伀鑺辨垚鍨嬫満", "sinker_edm"}, {"鐢电伀鑺卞皬瀛旀満", "edm_small_hole"}, {"鍑歌疆杞寸（", "camshaft_grinder"}, 
            {"绉伴噸寮忔贩鏂欐満", "gravimetric_blender"}, {"澶遍噸寮忓杺鏂欐満", "loss_in_weight_feeder"}, {"鏉跨墖鏉愭満", "sheet_line"}, {"锠曞姩娉电亴瑁呮満", "peristaltic_filler"}, 
            {"鍓戞潌缁囨満", "rapier_loom"}, {"鍠锋皵缁囨満", "air_jet_loom"}, {"鍠锋按缁囨満", "water_jet_loom"}, {"濉斿櫒", "tower_equipment"}, 
            {"鍙嶅嚮寮忕牬纰庢満", "impact_crusher"}, {"楂樼倝", "blast_furnace"}, {"鐢电倝", "electric_furnace"}, {"RH绮剧偧", "rh_degasser"}, 
            {"椋炲壀", "flying_shear"}, {"鐜荤拑绐戠倝", "glass_furnace"}, {"鐔旂獞", "melting_furnace"}, {"闄剁摲绐戠倝", "ceramic_kiln"}, 
            {"浜屼繚鐒婃満", "mag_welder"}, {"姘斾繚鐒婃満", "mig_welder"}, {"鍩嬪姬鐒婃満", "submerged_arc_welder"}, {"鐒婃帴骞冲彴", "welding_table"}, 
            {"闆嗕腑渚涙紗绯荤粺", "central_paint_supply"}, {"搴熸皵澶勭悊", "exhaust_treatment"}, {"RTO", "rto"}, {"RCO", "rco"}, 
            {"鏍兼爡", "bar_screen"}, {"涓夊潗鏍囨祴閲忔満", "coordinate_measuring_machine"}, {"鎽嗚疆鍒嗘嫞", "wheel_sorter"}, {"婊戝潡鍒嗘嫞", "shoe_sorter"}, 
            {"SCARA", "scara"}, {"RFID璇诲啓", "rfid"}, {"绔嬩綋浠撳簱", "asrs_warehouse"}, {"AMR", "amr"}, 
            {"缃楄尐椋庢満", "roots_blower"}, {"绂诲績椋庢満", "centrifugal_fan"}, {"杞存祦椋庢満", "axial_fan"}, {"鏂滄祦椋庢満", "mixed_flow_fan"}, 
            {"娣锋祦椋庢満", "mixed_flow_fan_2"}, {"椋庨榾", "air_damper"}, {"椋庡彛", "air_diffuser"}, {"闂搁榾", "gate_valve"}, 
            {"鐞冮榾", "ball_valve"}, {"铦堕榾", "butterfly_valve"}, {"RO鑶滃３", "ro_membrane_housing"}, {"鍔犺嵂瑁呯疆", "dosing_system"}, 
            {"SVG", "svg"}, {"濉斿悐", "tower_crane"}, {"鍗囬檷骞冲彴", "scissor_lift"}, {"绉诲姩骞冲彴", "mobile_platform"}, 
            {"骞宠溅", "flat_car"}, {"数控镗铣床", "cnc_boring_mill"}, {"数控龙门铣", "cnc_gantry_mill"}, {"数控刨床", "cnc_planer"}, 
            {"车铣复合加工中心", "mill_turn_machining_center"}, {"数控外圆磨", "cnc_cylindrical_grinder"}, {"数控内圆磨", "cnc_internal_grinder"}, {"数控平面磨", "cnc_surface_grinder"}, 
            {"数控无心磨", "cnc_centerless_grinder"}, {"数控珩磨机", "cnc_honing"}, {"数控研磨机", "cnc_lapping"}, {"数控抛光机", "cnc_polisher"}, 
            {"数控电火花", "cnc_edm"}, {"CNC磨床", "cnc_grinding"}, {"双主轴车床", "twin_spindle_lathe"}, {"双刀塔车床", "twin_turret_lathe"}, 
            {"走心机", "swiss_type_lathe"}, {"纵切车床", "sliding_head_lathe"}, {"复合磨床", "multi_function_grinder"}, {"切入磨", "plunge_grinder"}, 
            {"端面磨", "face_grinder"}, {"宽砂轮磨床", "wide_wheel_grinder"}, {"自动磨床", "auto_grinder"}, {"辊锻机", "roll_forging"}, 
            {"楔横轧机", "cross_wedge_rolling"}, {"辗环机", "ring_rolling"}, {"径向锻造机", "radial_forging"}, {"冷镦机", "cold_header"}, 
            {"热镦机", "hot_header"}, {"搓丝机", "thread_roller"}, {"滚丝机", "thread_rolling"}, {"弯管机", "pipe_bender"}, 
            {"弯弧机", "arc_bending"}, {"卷圆机", "circle_bending"}, {"调直机", "straightening_machine"}, {"切断机", "cutoff_machine"}, 
            {"剥皮机", "peeling_machine"}, {"倒棱机", "chamfering_machine_2"}, {"修磨机", "grinding_machine"}, {"橡胶密炼机", "rubber_internal_mixer"}, 
            {"橡胶压延机", "rubber_calender"}, {"橡胶注射机", "rubber_injection"}, {"轮胎硫化机", "tire_vulcanizer"}, {"胶囊硫化机", "bladder_vulcanizer"}, 
            {"硅胶挤出机", "silicone_extruder"}, {"造粒机组", "pelletizing_line"}, {"水环切粒机", "water_ring_pelletizer"}, {"水下切粒机", "underwater_pelletizer"}, 
            {"冷切粒机", "cold_pelletizer"}, {"磨粉机", "pulverizer"}, {"混炼机", "kneader"}, {"双辊开炼机", "two_roll_mill"}, 
            {"精密注塑机", "precision_injection"}, {"薄壁注塑机", "thin_wall_injection"}, {"高速注塑机", "high_speed_injection"}, {"搅拌炒锅", "stir_fry_cooker"}, 
            {"夹层锅", "jacketed_kettle"}, {"杀菌釜", "retort"}, {"喷淋杀菌釜", "spray_retort"}, {"水浴杀菌釜", "water_immersion_retort"}, 
            {"卧式杀菌釜", "horizontal_retort"}, {"微波杀菌机", "microwave_sterilizer"}, {"烟熏炉", "smokehouse"}, {"滚揉机", "tumbler"}, 
            {"注射腌制机", "brine_injector"}, {"嫩化机", "tenderizer"}, {"成型机械", "forming_press_2"}, {"螺柱焊", "stud_welding"}, 
            {"摩擦焊", "friction_welding"}, {"扩散焊", "diffusion_welding"}, {"钎焊机", "brazing_machine"}, {"高频钎焊机", "induction_brazing"}, 
            {"冷焊机", "cold_welder"}, {"废气洗涤塔", "exhaust_scrubber"}, {"活性炭吸附塔", "carbon_adsorption_tower"}, {"UV光解", "uv_photolysis"}, 
            {"生物除臭", "bio_deodorization"}, {"除雾器", "mist_eliminator"}, {"工业加湿器", "industrial_humidifier"}, {"转轮除湿机", "desiccant_dehumidifier"}, 
            {"冷库门", "cold_room_door"}, {"快速门", "high_speed_door"}, {"卷帘门", "roller_shutter"}, {"工业门", "industrial_door"}, 
            {"装卸平台", "dock_platform"}, {"液压登车桥", "hydraulic_dock_leveler"}, {"气袋式登车桥", "airbag_dock_leveler"}, {"升降货梯", "goods_lift"}, 
            {"移动升降机", "mobile_lift"}, {"曲臂升降机", "articulated_boom_lift"}, {"剪叉升降机", "scissor_lift_table"}, {"套缸升降机", "telescopic_lift"}, 
            {"导轨升降机", "guide_rail_lift"}, {"螺旋升降机", "screw_jack_lift"}, {"工业洗衣机", "industrial_washer"}, {"工业脱水机", "industrial_extractor"}, 
            {"工业烫平机", "industrial_flatwork_ironer"}, {"干洗机", "dry_cleaning_machine"}, {"空压机", "air_compressor"}, {"螺杆空压机", "screw_compressor"}, 
            {"活塞空压机", "piston_compressor"}, {"离心空压机", "centrifugal_compressor"}, {"无油空压机", "oil_free_compressor"}, {"冷冻式干燥机", "refrigerated_dryer"}, 
            {"吸附式干燥机", "desiccant_dryer"}, {"冷干机", "refrigerated_air_dryer"}, {"吸干机", "desiccant_air_dryer"}, {"储气罐", "air_receiver"}, 
            {"气水分离器", "air_water_separator"}, {"精密过滤器", "precision_filter"}, {"光学筛选机", "optical_sorter"}, {"视觉检测系统", "vision_inspection_system"}, 
            {"色选机", "color_sorter"}, {"称重分选机", "weight_sorter"}, {"金属分离器", "metal_separator"}, {"磁力架", "magnetic_grate"}, 
            {"永磁除铁器", "permanent_magnetic_separator"}, {"电磁除铁器", "electromagnetic_separator"}, {"涡电流分选机", "eddy_current_separator"}, {"减速器", "gearbox"}, 
            {"减速机", "reducer"}, {"变速器", "variator"}, {"联轴器", "coupling"}, {"离合器", "clutch"}, 
            {"制动器", "brake"}, {"万向节", "universal_joint"}, {"传动轴", "drive_shaft"}, {"丝杠", "lead_screw"}, 
            {"滚珠丝杠", "ball_screw"}, {"梯形丝杠", "acme_screw"}, {"同步带", "timing_belt"}, {"V带", "v_belt"}, 
            {"平带", "flat_belt"}, {"链条传动", "chain_drive"}, {"蜗轮蜗杆", "worm_gear"}, {"行星齿轮", "planetary_gear"}, 
            {"直齿轮", "spur_gear"}, {"斜齿轮", "helical_gear"}, {"锥齿轮", "bevel_gear"}, {"齿轮箱", "gear_box"}, 
            {"减速电机", "geared_motor"}, {"伺服电机", "servo_motor"}, {"步进电机", "stepper_motor"}, {"异步电机", "induction_motor"}, 
            {"同步电机", "synchronous_motor"}, {"直流电机", "dc_motor"}, {"交流电机", "ac_motor"}, {"变频电机", "vfd_motor"}, 
            {"力矩电机", "torque_motor"}, {"直线电机", "linear_motor"}, {"主轴电机", "spindle_motor"}, {"电主轴", "motorized_spindle"}, 
            {"电磁离合器", "electromagnetic_clutch"}, {"磁粉制动器", "magnetic_powder_brake"}, {"气动离合器", "pneumatic_clutch"}, {"花键轴", "spline_shaft"}, 
            {"曲轴", "crankshaft"}, {"凸轮轴", "camshaft"}, {"偏心轴", "eccentric_shaft"}, {"涨紧套", "taper_lock_bushing"}, 
            {"胀套", "expansion_sleeve"}, {"超越离合器", "overrunning_clutch"}, {"单向离合器", "one_way_clutch"}, {"电磁制动器", "electromagnetic_brake"}, 
            {"液压制动器", "hydraulic_brake"}, {"气动制动器", "pneumatic_brake"}, {"带式制动器", "band_brake"}, {"盘式制动器", "disc_brake"}, 
            {"鼓式制动器", "drum_brake"}, {"蜗轮减速机", "worm_reducer"}, {"行星减速机", "planetary_reducer"}, {"摆线针轮减速机", "cycloidal_reducer"}, 
            {"谐波减速器", "harmonic_reducer"}, {"伞齿轮", "bevel_gear"}, {"齿条", "rack"}, {"齿轮齿条", "rack_and_pinion"}, 
            {"链轮", "sprocket"}, {"皮带轮", "pulley"}, {"同步带轮", "timing_pulley"}, {"胀紧联结套", "locking_assembly"}, 
            {"弹性联轴器", "flexible_coupling"}, {"膜片联轴器", "diaphragm_coupling"}, {"梅花联轴器", "jaw_coupling"}, {"蛇形弹簧联轴器", "grid_coupling"}, 
            {"十字滑块联轴器", "oldham_coupling"}, {"万向联轴器", "universal_coupling"}, {"柱销联轴器", "pin_coupling"}, {"液力耦合器", "fluid_coupling"}, 
            {"数控机床", "cnc_machine"}, {"立式加工中心", "vertical_machining_center"}, {"卧式加工中心", "horizontal_machining_center"}, {"龙门加工中心", "gantry_machining_center"}, 
            {"五轴加工中心", "five_axis_machining_center"}, {"数控车床", "cnc_lathe"}, {"普通车床", "manual_lathe"}, {"立式车床", "vertical_lathe"}, 
            {"卧式车床", "horizontal_lathe"}, {"数控铣床", "cnc_milling"}, {"数控磨床", "cnc_grinder"}, {"平面磨床", "surface_grinder"}, 
            {"外圆磨床", "cylindrical_grinder"}, {"内圆磨床", "internal_grinder"}, {"无心磨床", "centerless_grinder"}, {"工具磨床", "tool_grinder"}, 
            {"螺纹磨床", "thread_grinder"}, {"齿轮磨床", "gear_grinder"}, {"坐标磨床", "jig_grinder"}, {"珩磨机", "honing_machine"}, 
            {"研磨机", "lapping_machine"}, {"电火花", "edm"}, {"线切割", "wire_cut_edm"}, {"慢走丝", "slow_wire_edm"}, 
            {"快走丝", "fast_wire_edm"}, {"中走丝", "medium_wire_edm"}, {"电火花成型机", "sinker_edm"}, {"电火花穿孔机", "hole_drilling_edm"}, 
            {"激光切割机", "laser_cutter"}, {"等离子切割机", "plasma_cutter"}, {"火焰切割机", "flame_cutter"}, {"水刀", "waterjet"}, 
            {"水切割", "waterjet_cutter"}, {"剪板机", "shearing_machine"}, {"卷板机", "plate_rolling_machine"}, {"校平机", "flattening_machine"}, 
            {"冲床", "punch_press"}, {"液压机", "hydraulic_press"}, {"油压机", "oil_press"}, {"压力机", "mechanical_press"}, 
            {"旋压机", "spinning_machine"}, {"拉伸机", "stretching_machine"}, {"滚齿机", "gear_hobbing_machine"}, {"插齿机", "gear_shaping_machine"}, 
            {"剃齿机", "gear_shaving_machine"}, {"磨齿机", "gear_grinding_machine"}, {"数控滚齿机", "cnc_gear_hobbing"}, {"数控插齿机", "cnc_gear_shaping"}, 
            {"摇臂钻", "radial_drill"}, {"台钻", "bench_drill"}, {"立式钻床", "upright_drill"}, {"数控钻床", "cnc_drill"}, 
            {"镗床", "boring_machine"}, {"卧式镗床", "horizontal_boring"}, {"落地镗床", "floor_boring"}, {"数控镗床", "cnc_boring"}, 
            {"刨床", "planer"}, {"龙门刨", "gantry_planer"}, {"牛头刨", "shaper"}, {"插床", "slotter"}, 
            {"拉床", "broaching_machine"}, {"圆锯机", "circular_saw"}, {"带锯床", "band_saw"}, {"弓锯床", "hacksaw"}, 
            {"电火花小孔机", "edm_small_hole"}, {"雕刻机", "engraving_machine"}, {"雕铣机", "engraving_milling"}, {"钻攻中心", "drill_tap_center"}, 
            {"车铣复合", "mill_turn_center"}, {"车削中心", "turning_center"}, {"龙门铣", "gantry_mill"}, {"双面铣", "double_face_mill"}, 
            {"端面铣", "end_face_mill"}, {"花键铣", "spline_milling"}, {"键槽铣", "keyway_milling"}, {"曲轴磨", "crankshaft_grinder"}, 
            {"凸轮轴磨", "camshaft_grinder"}, {"刀具磨", "cutter_grinder"}, {"拉刀磨", "broach_grinder"}, {"钻头磨", "drill_grinder"}, 
            {"锯片磨", "saw_blade_grinder"}, {"数控工具磨", "cnc_tool_grinder"}, {"电解加工", "electrochemical_machining"}, {"电化学去毛刺", "electrochemical_deburring"}, 
            {"激光打标机", "laser_marker"}, {"激光焊接机", "laser_welder"}, {"激光清洗机", "laser_cleaner"}, {"激光雕刻机", "laser_engraver"}, 
            {"数控弯管机", "cnc_pipe_bender"}, {"数控弹簧机", "cnc_spring_machine"}, {"数控绕线机", "cnc_coil_winder"}, {"砂轮机", "bench_grinder"}, 
            {"立式注塑机", "vertical_injection"}, {"卧式注塑机", "horizontal_injection"}, {"双色注塑机", "two_color_injection"}, {"全电动注塑机", "all_electric_injection"}, 
            {"挤塑机", "plastic_extruder"}, {"吹塑机", "blow_molding"}, {"吸塑机", "thermoforming"}, {"压铸机", "die_casting"}, 
            {"冷室压铸机", "cold_chamber_die_cast"}, {"热室压铸机", "hot_chamber_die_cast"}, {"橡胶硫化机", "rubber_vulcanizer"}, {"平板硫化机", "flat_vulcanizer"}, 
            {"注射硫化机", "injection_vulcanizer"}, {"密炼机", "internal_mixer"}, {"开炼机", "open_mill"}, {"压延机", "calender"}, 
            {"挤出机", "extruder_machine"}, {"双螺杆挤出机", "twin_screw_extruder"}, {"单螺杆挤出机", "single_screw_extruder"}, {"造粒机", "pelletizer"}, 
            {"切粒机", "granulator"}, {"破碎机", "shredder"}, {"混色机", "color_mixer"}, {"除湿干燥机", "dehumidifying_dryer"}, 
            {"模温机", "mold_temperature_controller"}, {"冷水机", "water_chiller"}, {"注塑机械手", "injection_robot"}, {"取出机", "picker"}, 
            {"上料机", "loader"}, {"自动上料机", "auto_loader"}, {"真空上料机", "vacuum_loader"}, {"热流道", "hot_runner"}, 
            {"冷流道", "cold_runner"}, {"合模机", "mold_clamping_machine"}, {"翻模机", "mold_turnover_machine"}, {"模具加热器", "mold_heater"}, 
            {"机边粉碎机", "beside_press_crusher"}, {"中央供料", "central_feeding"}, {"比例混合器", "ratio_mixer"}, {"称重式混料机", "gravimetric_blender"}, 
            {"失重式喂料机", "loss_in_weight_feeder"}, {"色母机", "masterbatch_feeder"}, {"挤出造粒线", "extrusion_pelletizing_line"}, {"吹膜机", "film_blowing"}, 
            {"流延膜机", "cast_film"}, {"拉伸膜机", "stretch_film"}, {"热收缩膜机", "heat_shrink_film"}, {"制杯机", "cup_forming"}, 
            {"片材挤出机", "sheet_extruder"}, {"板片材机", "sheet_line"}, {"管材挤出机", "pipe_extruder"}, {"异型材挤出机", "profile_extruder"}, 
            {"橡胶挤出机", "rubber_extruder"}, {"胶管挤出线", "hose_extrusion_line"}, {"和面机", "dough_mixer"}, {"斩拌机", "chopper_mixer"}, 
            {"绞肉机", "meat_grinder"}, {"切丁机", "dicer"}, {"切片机", "slicer"}, {"切丝机", "shredder_machine"}, 
            {"切菜机", "vegetable_cutter"}, {"打浆机", "pulper"}, {"磨浆机", "refiner"}, {"均质机", "homogenizer_machine"}, 
            {"乳化机", "emulsifier"}, {"脱气机", "deaerator"}, {"杀菌机", "pasteurizer"}, {"巴氏杀菌机", "batch_pasteurizer"}, 
            {"UHT杀菌机", "uht_sterilizer"}, {"液体灌装机", "liquid_filler"}, {"膏体灌装机", "paste_filler"}, {"粉末灌装机", "powder_filler"}, 
            {"颗粒灌装机", "granule_filler"}, {"旋盖机", "capper"}, {"喷码机", "inkjet_printer"}, {"激光打码机", "laser_coder"}, 
            {"套标机", "sleeve_labeler"}, {"收缩包装机", "shrink_wrapper"}, {"裹包机", "overwrapper"}, {"打包机", "baler"}, 
            {"封箱机", "case_sealer"}, {"开箱机", "case_erector"}, {"码垛机", "palletizer"}, {"蒸煮机", "cooker"}, 
            {"油炸机", "fryer"}, {"烘烤机", "baking_oven"}, {"速冻机", "quick_freezer"}, {"真空包装机", "vacuum_packer"}, 
            {"气调包装机", "map_packaging"}, {"枕式包装机", "pillow_packer"}, {"立式包装机", "vertical_packer"}, {"给袋式包装机", "bag_in_box_packer"}, 
            {"全自动灌装线", "auto_filling_line"}, {"吹干机", "air_dryer"}, {"洗瓶机", "bottle_washer"}, {"洗罐机", "can_washer"}, 
            {"负压灌装机", "vacuum_filler"}, {"等压灌装机", "isobaric_filler"}, {"蠕动泵灌装机", "peristaltic_filler"}, {"柱塞式灌装机", "piston_filler"}, 
            {"感应封口机", "induction_sealer"}, {"热收缩炉", "shrink_tunnel"}, {"解冻机", "thawing_machine"}, {"刨片机", "slicing_machine"}, 
            {"斩切机", "chopping_cutter"}, {"去鳞机", "descaler"}, {"去皮机", "peeler"}, {"去核机", "pitter"}, 
            {"榨汁机", "juice_extractor"}, {"浓缩蒸发器", "concentration_evaporator"}, {"板式杀菌机", "plate_pasteurizer"}, {"管式杀菌机", "tubular_pasteurizer"}, 
            {"压片机", "tablet_press"}, {"高速压片机", "high_speed_tablet_press"}, {"胶囊填充机", "capsule_filler"}, {"制粒机", "granulator_machine"}, 
            {"湿法制粒机", "wet_granulator"}, {"干法制粒机", "dry_granulator"}, {"沸腾制粒机", "fluid_bed_granulator"}, {"包衣机", "coating_machine"}, 
            {"高效包衣机", "high_efficiency_coater"}, {"糖衣机", "sugar_coater"}, {"三维混合机", "three_d_mixer"}, {"V型混合机", "v_mixer"}, 
            {"槽型混合机", "trough_mixer"}, {"整粒机", "size_reducer"}, {"流化床", "fluid_bed"}, {"流化床干燥机", "fluid_bed_dryer"}, 
            {"冻干机", "freeze_dryer"}, {"灭菌柜", "sterilizer_cabinet"}, {"灭菌隧道", "sterilizing_tunnel"}, {"安瓿灌装机", "ampoule_filler"}, 
            {"西林瓶灌装机", "vial_filler"}, {"口服液灌装机", "oral_liquid_filler"}, {"软胶囊机", "softgel_machine"}, {"灯检机", "visual_inspection"}, 
            {"自动灯检机", "auto_visual_inspection"}, {"装盒机", "cartoner"}, {"泡罩包装机", "blister_packer"}, {"铝塑包装机", "alu_plastic_packer"}, 
            {"枕包机", "pouch_packer"}, {"中盒包装机", "outer_cartoner"}, {"铝塑泡罩机", "blister_machine"}, {"胶囊抛光机", "capsule_polisher"}, 
            {"胶囊分选机", "capsule_sorter"}, {"胶囊印字机", "capsule_printer"}, {"片剂除粉机", "tablet_deduster"}, {"片剂金属检测", "tablet_metal_detector"}, 
            {"提升上料机", "elevator_feeder"}, {"万能粉碎机", "universal_crusher"}, {"超微粉碎机", "micronizer"}, {"气流粉碎机", "jet_mill"}, 
            {"球磨机", "ball_mill_machine"}, {"湿法研磨机", "wet_mill"}, {"高压均质机", "high_pressure_homogenizer"}, {"溶出仪", "dissolution_tester"}, 
            {"崩解仪", "disintegration_tester"}, {"脆碎度仪", "friability_tester"}, {"澄明度检测仪", "clarity_tester"}, {"灭菌烘箱", "sterilization_oven"}, 
            {"干热灭菌柜", "dry_heat_sterilizer"}, {"湿热灭菌柜", "moist_heat_sterilizer"}, {"环氧乙烷灭菌器", "eo_sterilizer"}, {"臭氧灭菌器", "ozone_sterilizer"}, 
            {"纺纱机", "spinning_frame"}, {"环锭纺", "ring_spinning_frame"}, {"气流纺", "rotor_spinning"}, {"涡流纺", "vortex_spinning"}, 
            {"紧密纺", "compact_spinning"}, {"粗纱机", "roving_frame"}, {"细纱机", "ring_frame"}, {"络筒机", "winder"}, 
            {"整经机", "warper"}, {"浆纱机", "sizing_machine"}, {"织布机", "loom"}, {"剑杆织机", "rapier_loom"}, 
            {"喷气织机", "air_jet_loom"}, {"喷水织机", "water_jet_loom"}, {"片梭织机", "projectile_loom"}, {"针织机", "knitting_machine"}, 
            {"圆机", "circular_knitter"}, {"横机", "flat_knitter"}, {"经编机", "warp_knitter"}, {"纬编机", "weft_knitter"}, 
            {"袜机", "sock_knitter"}, {"染色机", "dyeing_machine"}, {"溢流染色机", "overflow_dyeing"}, {"气流染色机", "airflow_dyeing"}, 
            {"卷染机", "jigger"}, {"定型机", "stenter_machine"}, {"拉幅定型机", "stenter_frame"}, {"预缩机", "sanforizer"}, 
            {"起毛机", "raising_machine"}, {"磨毛机", "sueding_machine"}, {"剪毛机", "shearing_machine"}, {"刷毛机", "brushing_machine"}, 
            {"烧毛机", "singeing_machine"}, {"丝光机", "mercerizing_machine"}, {"退浆机", "desizing_machine"}, {"煮练机", "scouring_machine"}, 
            {"漂白机", "bleaching_machine"}, {"印花机", "printing_machine"}, {"圆网印花机", "rotary_screen_printer"}, {"平网印花机", "flat_screen_printer"}, 
            {"数码印花机", "digital_printer"}, {"转移印花机", "transfer_printer"}, {"蒸化机", "steamer"}, {"水洗机", "washing_machine"}, 
            {"烘干机", "tumble_dryer"}, {"拉链机", "zipper_machine"}, {"缝纫机", "sewing_machine"}, {"开幅机", "opener"}, 
            {"脱水机", "hydro_extractor"}, {"蓬松机", "loosener"}, {"抓棉机", "bale_plucker"}, {"开棉机", "opener_machine"}, 
            {"清棉机", "scutcher"}, {"精梳机", "comber"}, {"并纱机", "doubler"}, {"倍捻机", "two_for_one_twister"}, 
            {"捻线机", "twister_machine"}, {"分条整经机", "sectional_warper"}, {"结经机", "knotting_machine"}, {"验布机", "fabric_inspector"}, 
            {"折布机", "fabric_folding"}, {"轧液机", "padding_machine"}, {"印刷机", "printing_press"}, {"胶印机", "offset_printer"}, 
            {"凹印机", "gravure_printer"}, {"柔印机", "flexo_printer"}, {"丝印机", "screen_printer"}, {"移印机", "pad_printer"}, 
            {"数码印刷机", "digital_press"}, {"标签印刷机", "label_printer"}, {"商标印刷机", "trademark_printer"}, {"模切机", "die_cutter"}, 
            {"烫金机", "hot_stamper"}, {"覆膜机", "laminator"}, {"裱纸机", "paper_mounter"}, {"糊盒机", "box_gluer"}, 
            {"钉箱机", "box_stitcher"}, {"瓦楞机", "corrugator"}, {"单面机", "single_facer"}, {"横切机", "cross_cutter"}, 
            {"分切机", "slitter"}, {"复卷机", "rewinder"}, {"检品机", "inspection_machine"}, {"品检机", "quality_inspector"}, 
            {"制袋机", "bag_maker"}, {"流延机", "casting_machine"}, {"涂布机", "coater"}, {"复合机", "laminating_machine"}, 
            {"干式复合机", "dry_laminator"}, {"湿式复合机", "wet_laminator"}, {"无溶剂复合机", "solvent_free_laminator"}, {"切纸机", "paper_cutter"}, 
            {"糊箱机", "box_gluing"}, {"贴窗机", "window_patcher"}, {"上光机", "varnishing_machine"}, {"压光机", "calendering_machine"}, 
            {"烫印机", "foil_stamper"}, {"压痕机", "creasing_machine"}, {"包背机", "perfect_binder"}, {"胶装联动线", "perfect_binding_line"}, 
            {"骑马订", "saddle_stitcher"}, {"配页机", "collator"}, {"折页机", "folder"}, {"锁线机", "thread_sewing"}, 
            {"精装联动线", "hardcover_line"}, {"反应器", "chemical_reactor"}, {"搅拌釜", "stirred_tank"}, {"聚合釜", "polymerization_kettle"}, 
            {"结晶器", "crystallizer"}, {"蒸发器", "evaporator"}, {"降膜蒸发器", "falling_film_evaporator"}, {"强制循环蒸发器", "forced_circulation_evaporator"}, 
            {"精馏塔", "rectification_column"}, {"吸收塔", "absorption_tower"}, {"干燥塔", "drying_tower"}, {"喷雾干燥塔", "spray_dryer"}, 
            {"离心干燥机", "centrifugal_dryer"}, {"真空干燥机", "vacuum_dryer"}, {"双锥干燥机", "double_cone_dryer"}, {"耙式干燥机", "rake_dryer"}, 
            {"盘式干燥机", "disc_dryer"}, {"闪蒸干燥机", "flash_dryer"}, {"卧螺离心机", "decanter_centrifuge"}, {"碟式离心机", "disc_centrifuge"}, 
            {"管式离心机", "tubular_centrifuge"}, {"过滤机", "filter_machine"}, {"板框过滤机", "plate_frame_filter"}, {"带式过滤机", "belt_filter"}, 
            {"真空过滤机", "vacuum_filter"}, {"压滤机", "filter_press"}, {"膜分离设备", "membrane_separation"}, {"萃取塔", "extraction_column"}, 
            {"萃取器", "extractor"}, {"换热器", "heat_exchanger_unit"}, {"列管换热器", "shell_tube_exchanger"}, {"板式换热器", "plate_exchanger"}, 
            {"螺旋板换热器", "spiral_plate_exchanger"}, {"石墨换热器", "graphite_exchanger"}, {"冷凝器", "condenser"}, {"凉水塔", "cooling_water_tower"}, 
            {"塔器", "tower_equipment"}, {"储罐", "storage_tank"}, {"搅拌罐", "mixing_tank"}, {"缓冲罐", "buffer_tank"}, 
            {"计量罐", "metering_tank"}, {"高位槽", "head_tank"}, {"蒸馏釜", "distillation_kettle"}, {"脱气塔", "degassing_tower"}, 
            {"汽提塔", "stripping_column"}, {"洗涤塔", "scrubber"}, {"湍球塔", "turbulent_ball_tower"}, {"鼓泡塔", "bubble_column"}, 
            {"环流反应器", "loop_reactor"}, {"固定床反应器", "fixed_bed_reactor"}, {"流化床反应器", "fluidized_bed_reactor"}, {"颚式破碎机", "jaw_crusher"}, 
            {"反击式破碎机", "impact_crusher"}, {"锤式破碎机", "hammer_crusher"}, {"圆锥破碎机", "cone_crusher"}, {"对辊破碎机", "double_roll_crusher"}, 
            {"棒磨机", "rod_mill"}, {"自磨机", "autogenous_mill"}, {"半自磨机", "sag_mill"}, {"雷蒙磨", "raymond_mill"}, 
            {"超细磨", "ultrafine_mill"}, {"振动筛", "vibrating_screen"}, {"圆振动筛", "circular_vibrating_screen"}, {"直线振动筛", "linear_vibrating_screen"}, 
            {"滚筒筛", "trommel_screen"}, {"分级机", "classifier_machine"}, {"螺旋分级机", "spiral_classifier"}, {"旋流器", "cyclone"}, 
            {"水力旋流器", "hydrocyclone"}, {"浮选机", "flotation_machine"}, {"磁选机", "magnetic_separator"}, {"跳汰机", "jig"}, 
            {"摇床", "shaking_table"}, {"螺旋溜槽", "spiral_chute"}, {"浓缩机", "thickener"}, {"浓密机", "thickener_tank"}, 
            {"陶瓷过滤机", "ceramic_filter"}, {"圆盘造粒机", "disc_pelletizer"}, {"竖炉", "shaft_furnace"}, {"焙烧炉", "roaster"}, 
            {"给料机", "feeder_machine"}, {"振动给料机", "vibrating_feeder"}, {"板式给料机", "apron_feeder"}, {"皮带输送机", "belt_conveyor_machine"}, 
            {"刮板输送机", "scraper_conveyor"}, {"斗式提升机", "bucket_elevator"}, {"螺旋输送机", "screw_conveyor"}, {"装载机", "loader_machine"}, 
            {"挖掘机", "excavator"}, {"推土机", "bulldozer"}, {"给煤机", "coal_feeder"}, {"破碎站", "crushing_station"}, 
            {"移动破碎站", "mobile_crusher"}, {"液压破碎锤", "hydraulic_breaker"}, {"除铁器", "iron_remover"}, {"皮带秤", "belt_scale"}, 
            {"取样机", "sampler"}, {"高炉", "blast_furnace"}, {"转炉", "converter"}, {"电炉", "electric_furnace"}, 
            {"精炼炉", "refining_furnace"}, {"LF炉", "ladle_furnace"}, {"RH精炼", "rh_degasser"}, {"连铸机", "continuous_caster"}, 
            {"方坯连铸机", "billet_caster"}, {"板坯连铸机", "slab_caster"}, {"轧机", "rolling_mill"}, {"热轧机", "hot_rolling_mill"}, 
            {"冷轧机", "cold_rolling_mill"}, {"带钢轧机", "strip_mill"}, {"棒材轧机", "bar_mill"}, {"线材轧机", "wire_rod_mill"}, 
            {"型钢轧机", "section_mill"}, {"钢管轧机", "pipe_mill"}, {"剪切机", "shear"}, {"飞剪", "flying_shear"}, 
            {"定尺剪", "cut_to_length_shear"}, {"冷床", "cooling_bed"}, {"罩式退火炉", "bell_annealer"}, {"连续退火炉", "continuous_annealer"}, 
            {"镀锌线", "galvanizing_line"}, {"镀锡线", "tinplating_line"}, {"彩涂线", "color_coating_line"}, {"酸洗线", "pickling_line"}, 
            {"酸洗槽", "pickling_tank"}, {"酸再生", "acid_regeneration"}, {"轧辊磨床", "roll_grinder"}, {"破鳞机", "scale_breaker"}, 
            {"拉矫机", "tension_leveler"}, {"平整机", "skin_pass_mill"}, {"切边机", "edge_trimmer"}, {"纵剪机", "slitting_machine"}, 
            {"横剪机", "cross_shearing"}, {"卷取机", "coiler"}, {"开卷机", "uncoiler"}, {"活套", "looper"}, 
            {"焊管机", "pipe_welder"}, {"高频焊管机", "high_frequency_pipe_mill"}, {"玻璃窑炉", "glass_furnace"}, {"熔窑", "melting_furnace_2"}, 
            {"退火窑", "annealing_lehr"}, {"钢化炉", "tempering_furnace_glass"}, {"夹胶线", "laminating_line"}, {"中空线", "insulating_glass_line"}, 
            {"镀膜线", "coating_line"}, {"磨边机", "edge_grinder"}, {"钻孔机", "drilling_machine"}, {"玻璃清洗机", "glass_washer"}, 
            {"陶瓷窑炉", "ceramic_kiln"}, {"隧道窑", "tunnel_kiln"}, {"辊道窑", "roller_kiln"}, {"梭式窑", "shuttle_kiln"}, 
            {"陶瓷压机", "ceramic_press"}, {"成型机", "forming_machine"}, {"施釉机", "glazing_machine"}, {"玻璃磨边机", "glass_edger"}, 
            {"玻璃钻孔机", "glass_driller"}, {"玻璃异形磨边机", "glass_shape_edger"}, {"玻璃双直边机", "glass_double_edger"}, {"玻璃双边机", "glass_bilateral_edger"}, 
            {"玻璃斜边机", "glass_beveler"}, {"玻璃圆边机", "glass_round_edger"}, {"异形切割机", "shape_cutter"}, {"等静压机", "isostatic_press"}, 
            {"挤出成型机", "extrusion_former"}, {"注浆成型", "slip_casting"}, {"热压成型机", "hot_press_former"}, {"施釉线", "glazing_line"}, 
            {"推台锯", "sliding_table_saw"}, {"精密锯", "precision_saw"}, {"带锯机", "band_saw_machine"}, {"木工带锯", "wood_band_saw"}, 
            {"多片锯", "multi_rip_saw"}, {"四面刨", "four_sided_planer"}, {"平刨", "surface_planer"}, {"压刨", "thickness_planer"}, 
            {"双面刨", "double_side_planer"}, {"砂光机", "sander"}, {"宽带砂光机", "wide_belt_sander"}, {"异形砂光机", "profile_sander"}, 
            {"仿形铣", "copy_milling"}, {"木工铣床", "wood_milling"}, {"数控雕刻机", "cnc_router"}, {"木工雕刻机", "wood_cnc_router"}, 
            {"开榫机", "tenoner"}, {"榫槽机", "mortiser"}, {"打孔机", "boring_machine"}, {"多排钻", "multi_boring"}, 
            {"封边机", "edge_bander"}, {"手动封边机", "manual_edge_bander"}, {"自动封边机", "auto_edge_bander"}, {"曲直封边机", "curved_edge_bander"}, 
            {"CNC加工中心", "cnc_machining_center"}, {"木工加工中心", "wood_machining_center"}, {"排钻", "line_boring"}, {"拼板机", "panel_splicer"}, 
            {"冷压机", "cold_press"}, {"热压机", "hot_press"}, {"高频拼板机", "high_frequency_splicer"}, {"涂胶机", "glue_spreader"}, 
            {"淋幕机", "curtain_coater"}, {"辊涂机", "roller_coater"}, {"喷涂机", "spray_machine"}, {"UV干燥机", "uv_dryer"}, 
            {"精密推台锯", "precision_sliding_saw"}, {"电子开料锯", "electronic_panel_saw"}, {"数控裁板锯", "cnc_panel_saw"}, {"镂铣机", "router_machine"}, 
            {"曲线锯", "jigsaw"}, {"往复锯", "reciprocating_saw"}, {"双端铣", "double_end_tenoner"}, {"榫头机", "tenoning_machine"}, 
            {"铰链钻孔机", "hinge_boring"}, {"真空覆膜机", "vacuum_membrane_press"}, {"包覆机", "profile_wrapper"}, {"电焊机", "arc_welder"}, 
            {"氩弧焊机", "tig_welder"}, {"二保焊机", "mag_welder"}, {"气保焊机", "mig_welder"}, {"埋弧焊机", "submerged_arc_welder"}, 
            {"等离子焊机", "plasma_welder"}, {"激光焊机", "laser_welding_machine"}, {"点焊机", "spot_welder"}, {"凸焊机", "projection_welder"}, 
            {"缝焊机", "seam_welder"}, {"对焊机", "butt_welder"}, {"碰焊机", "flash_welder"}, {"电阻焊机", "resistance_welder"}, 
            {"焊接机器人", "welding_robot"}, {"焊烟净化器", "fume_extractor"}, {"变位机", "positioner"}, {"焊接变位机", "welding_positioner"}, 
            {"焊接平台", "welding_table"}, {"滚轮架", "roller_bed"}, {"焊接滚轮架", "welding_rotator"}, {"坡口机", "beveller"}, 
            {"数控切割机", "cnc_cutter"}, {"便携式数控切割机", "portable_cnc_cutter"}, {"相贯线切割机", "pipe_intersection_cutter"}, {"焊接专机", "special_welding_machine"}, 
            {"螺柱焊机", "stud_welder"}, {"摩擦焊机", "friction_welder"}, {"超声波焊机", "ultrasonic_welder"}, {"电子束焊机", "electron_beam_welder"}, 
            {"喷涂线", "spray_line"}, {"喷漆线", "paint_line"}, {"喷粉线", "powder_coating_line"}, {"电泳线", "ed_coating_line"}, 
            {"前处理线", "pretreatment_line"}, {"涂装机器人", "painting_robot"}, {"自动喷涂机", "automatic_sprayer"}, {"手动喷枪", "manual_spray_gun"}, 
            {"自动喷枪", "auto_spray_gun"}, {"静电喷涂", "electrostatic_spray"}, {"粉末喷涂", "powder_coating"}, {"无气喷涂", "airless_spray"}, 
            {"空气喷涂", "air_spray"}, {"混气喷涂", "air_assisted_spray"}, {"烘干炉", "drying_oven"}, {"烤漆房", "paint_booth"}, 
            {"喷砂房", "sandblasting_room"}, {"抛丸机", "shot_blaster"}, {"除锈机", "derusting_machine"}, {"超声波清洗机", "ultrasonic_cleaner"}, 
            {"高压清洗机", "high_pressure_washer"}, {"喷锌机", "arc_spray"}, {"喷铝机", "aluminum_spray"}, {"热喷涂", "thermal_spray"}, 
            {"超音速喷涂", "hvof_spray"}, {"等离子喷涂", "plasma_spray"}, {"集中供漆系统", "central_paint_supply"}, {"除尘器", "dust_collector"}, 
            {"布袋除尘器", "baghouse"}, {"脉冲除尘器", "pulse_jet_collector"}, {"旋风除尘器", "cyclone_dust_collector"}, {"静电除尘器", "electrostatic_precipitator"}, 
            {"脱硫塔", "desulfurization_tower"}, {"脱硝装置", "denox_system"}, {"废气处理", "exhaust_treatment"}, {"活性炭吸附", "activated_carbon_adsorption"}, 
            {"生物滤池", "biofilter"}, {"曝气池", "aeration_tank"}, {"沉淀池", "sedimentation_tank"}, {"污泥脱水机", "sludge_dewaterer"}, 
            {"带式脱水机", "belt_dewaterer"}, {"离心脱水机", "centrifugal_dewaterer"}, {"板框压滤机", "plate_frame_press"}, {"叠螺机", "screw_press_dewaterer"}, 
            {"刮泥机", "sludge_scraper"}, {"格栅", "bar_screen"}, {"格栅除污机", "screen_cleaner"}, {"固液分离机", "solid_liquid_separator"}, 
            {"油水分离器", "oil_water_separator"}, {"隔油池", "oil_trap"}, {"气浮机", "daf_system"}, {"一体化设备", "integrated_equipment"}, 
            {"催化燃烧", "catalytic_oxidation"}, {"沸石转轮", "zeolite_rotor"}, {"蓄热式焚烧炉", "regenerative_oxidizer"}, {"低温等离子", "cold_plasma"}, 
            {"光催化氧化", "photocatalytic_oxidation"}, {"三坐标", "cmm"}, {"三坐标测量机", "coordinate_measuring_machine"}, {"影像测量仪", "vision_measuring"}, 
            {"投影仪", "profile_projector"}, {"测高仪", "height_gauge"}, {"粗糙度仪", "roughness_tester"}, {"轮廓仪", "profilometer"}, 
            {"圆度仪", "roundness_tester"}, {"硬度计", "hardness_tester"}, {"洛氏硬度计", "rockwell_tester"}, {"维氏硬度计", "vickers_tester"}, 
            {"布氏硬度计", "brinell_tester"}, {"直读光谱仪", "oes_spectrometer"}, {"手持光谱仪", "handheld_spectrometer"}, {"拉力试验机", "tensile_tester"}, 
            {"万能试验机", "universal_tester"}, {"疲劳试验机", "fatigue_tester"}, {"冲击试验机", "impact_tester"}, {"扭转试验机", "torsion_tester"}, 
            {"X光探伤", "x_ray_ndt"}, {"超声波探伤", "ultrasonic_ndt"}, {"涡流探伤", "eddy_current_ndt"}, {"磁粉探伤", "magnetic_particle_ndt"}, 
            {"渗透探伤", "penetrant_ndt"}, {"检漏仪", "leak_detector"}, {"氦检漏", "helium_leak_detector"}, {"气密性检测", "airtightness_test"}, 
            {"盐雾试验箱", "salt_spray_chamber"}, {"恒温恒湿箱", "climate_chamber"}, {"振动台", "vibration_table"}, {"跌落试验机", "drop_tester"}, 
            {"金相显微镜", "metallographic_microscope"}, {"体视显微镜", "stereo_microscope"}, {"对刀仪", "tool_setter"}, {"球杆仪", "ballbar"}, 
            {"激光干涉仪", "laser_interferometer"}, {"红外热像仪", "thermal_imager"}, {"涂层测厚仪", "coating_thickness_gauge"}, {"超声波测厚仪", "ultrasonic_thickness_gauge"}, 
            {"弹簧试验机", "spring_tester"}, {"平衡机", "balancing_machine"}, {"探伤仪", "flaw_detector"}, {"内窥镜", "borescope"}, 
            {"工业内窥镜", "industrial_borescope"}, {"影像仪", "video_measuring"}, {"RGV", "rgv"}, {"交叉带分拣", "cross_belt_sorter"}, 
            {"摆轮分拣", "wheel_sorter"}, {"滑块分拣", "shoe_sorter"}, {"拆垛机器人", "depalletizing_robot"}, {"桁架机械手", "gantry_robot"}, 
            {"关节机器人", "articulated_robot"}, {"协作机器人", "collaborative_robot"}, {"Delta机器人", "delta_robot"}, {"并联机器人", "parallel_robot"}, 
            {"直角坐标机器人", "cartesian_robot"}, {"桁架机器人", "gantry_manipulator"}, {"视觉系统", "vision_system"}, {"条码扫描", "barcode_scan"}, 
            {"RFID读写", "rfid"}, {"电子标签", "pick_to_light"}, {"立体仓库", "asrs_warehouse"}, {"智能柜", "smart_cabinet"}, 
            {"转运车", "transfer_cart"}, {"往复式提升机", "reciprocating_elevator"}, {"连续式提升机", "continuous_elevator"}, {"倍速链", "double_speed_chain"}, 
            {"旋转台", "turntable"}, {"移载机", "transfer_unit"}, {"顶升移载", "lift_transfer"}, {"称重设备", "weighing_system"}, 
            {"体积测量", "dimensioning_system"}, {"DWS系统", "dws_system"}, {"无人叉车", "agv_forklift"}, {"自主移动机器人", "amr"}, 
            {"料箱机器人", "tote_robot"}, {"地牛搬运", "pallet_truck"}, {"冷水机组", "chiller_unit"}, {"风冷机组", "air_cooled_chiller"}, 
            {"水冷机组", "water_cooled_chiller"}, {"螺杆机组", "screw_chiller"}, {"离心机组", "centrifugal_chiller"}, {"冷却水泵", "cooling_water_pump"}, 
            {"冷冻水泵", "chilled_water_pump"}, {"空调机组", "air_handler"}, {"组合式空调", "ahu"}, {"新风机组", "fresh_air_unit"}, 
            {"风机盘管", "fan_coil_unit"}, {"多联机", "vrf"}, {"分体空调", "split_ac"}, {"恒温恒湿机", "constant_climate_unit"}, 
            {"除湿机", "dehumidifier"}, {"加湿器", "humidifier"}, {"冷风机", "air_cooler"}, {"暖风机", "unit_heater"}, 
            {"空气幕", "air_curtain"}, {"风幕机", "air_curtain_unit"}, {"排风机", "exhaust_fan"}, {"送风机", "supply_fan"}, 
            {"引风机", "induced_draft_fan"}, {"鼓风机", "blower"}, {"罗茨风机", "roots_blower"}, {"离心风机", "centrifugal_fan"}, 
            {"轴流风机", "axial_fan"}, {"斜流风机", "mixed_flow_fan"}, {"混流风机", "mixed_flow_fan_2"}, {"风阀", "air_damper"}, 
            {"防火阀", "fire_damper"}, {"排烟阀", "smoke_damper"}, {"消声器", "silencer"}, {"静压箱", "plenum_box"}, 
            {"风口", "air_diffuser"}, {"散流器", "diffuser"}, {"风口百叶", "grille"}, {"离心泵", "centrifugal_pump"}, 
            {"潜水泵", "submersible_pump"}, {"深井泵", "deep_well_pump"}, {"自吸泵", "self_priming_pump"}, {"化工泵", "chemical_pump"}, 
            {"磁力泵", "magnetic_drive_pump"}, {"隔膜泵", "diaphragm_pump"}, {"计量泵", "metering_pump"}, {"螺杆泵", "screw_pump"}, 
            {"齿轮泵", "gear_pump"}, {"水环真空泵", "water_ring_pump"}, {"罗茨真空泵", "roots_vacuum_pump"}, {"旋片真空泵", "rotary_vane_pump"}, 
            {"扩散泵", "diffusion_pump"}, {"分子泵", "turbo_pump"}, {"闸阀", "gate_valve"}, {"截止阀", "globe_valve"}, 
            {"球阀", "ball_valve"}, {"蝶阀", "butterfly_valve"}, {"止回阀", "check_valve"}, {"安全阀", "safety_valve"}, 
            {"减压阀", "reducing_valve"}, {"疏水阀", "steam_trap"}, {"调节阀", "control_valve"}, {"电动阀", "electric_valve"}, 
            {"气动阀", "pneumatic_valve"}, {"电磁阀", "solenoid_valve"}, {"比例阀", "proportional_valve"}, {"陶瓷阀", "ceramic_valve"}, 
            {"衬氟阀", "ptfe_lined_valve"}, {"卫生级阀门", "sanitary_valve"}, {"过滤器", "filter"}, {"Y型过滤器", "y_strainer"}, 
            {"自清洗过滤器", "self_cleaning_filter"}, {"砂滤器", "sand_filter_vessel"}, {"碳滤器", "carbon_filter_vessel"}, {"软化器", "softener"}, 
            {"反渗透膜", "ro_membrane"}, {"超滤膜", "uf_membrane"}, {"RO膜壳", "ro_membrane_housing"}, {"保安过滤器", "security_filter"}, 
            {"加药装置", "dosing_system"}, {"配电柜", "power_cabinet"}, {"开关柜", "switchgear"}, {"配电箱", "distribution_box"}, 
            {"控制箱", "control_box"}, {"操作台", "operator_station"}, {"伺服驱动器", "servo_drive"}, {"软启动器", "soft_starter"}, 
            {"UPS", "ups"}, {"稳压电源", "regulated_power"}, {"直流电源", "dc_power_supply"}, {"变频电源", "variable_frequency_power"}, 
            {"发电机", "generator"}, {"柴油发电机", "diesel_generator"}, {"汽轮发电机", "steam_turbine_generator"}, {"电动机", "electric_motor"}, 
            {"防爆电机", "explosion_proof_motor"}, {"高压柜", "high_voltage_cabinet"}, {"低压柜", "low_voltage_cabinet"}, {"电容柜", "capacitor_bank"}, 
            {"进线柜", "incoming_cabinet"}, {"出线柜", "outgoing_cabinet"}, {"母联柜", "bus_tie_cabinet"}, {"计量柜", "metering_cabinet"}, 
            {"PT柜", "pt_cabinet"}, {"变频柜", "vfd_cabinet"}, {"软启柜", "soft_starter_cabinet"}, {"配电盘", "switchboard"}, 
            {"动力柜", "power_distribution_cabinet"}, {"照明箱", "lighting_box"}, {"检修箱", "maintenance_box"}, {"直流屏", "dc_panel"}, 
            {"EPS电源", "eps"}, {"有源滤波器", "active_filter"}, {"电缆桥架", "cable_tray"}, {"母线槽", "bus_duct"}, 
            {"叉车", "forklift"}, {"电动叉车", "electric_forklift"}, {"堆高车", "stacker_truck"}, {"搬运车", "pallet_jack"}, 
            {"手动液压车", "manual_pallet_truck"}, {"起重机", "crane"}, {"行车", "overhead_crane"}, {"天车", "bridge_crane"}, 
            {"龙门吊", "gantry_crane"}, {"塔吊", "tower_crane"}, {"汽车吊", "mobile_crane"}, {"电动葫芦", "electric_hoist"}, 
            {"环链葫芦", "chain_hoist"}, {"绞车", "winch"}, {"卷扬机", "hoist"}, {"升降机", "lift"}, 
            {"电梯", "elevator"}, {"载货电梯", "freight_elevator"}, {"液压升降台", "hydraulic_lift"}, {"堆垛车", "reach_truck"}, 
            {"登车桥", "dock_leveler"}, {"升降平台", "scissor_lift"}, {"移动平台", "mobile_platform"}, {"悬臂吊", "jib_crane"}, 
            {"壁行吊", "wall_crane"}, {"平车", "flat_car"}, {"轨道车", "rail_car"}, {"工业风扇", "industrial_fan"}, 
            {"工具柜", "tool_cabinet"}, {"工作台", "workbench"}, {"台虎钳", "bench_vise"},
            {"臂", "arm"}, {"腿", "leg"}, {"头", "head"}, {"尾", "tail"},
            {"辊", "roller"}, {"轴", "shaft"}, {"轮", "wheel"}, {"轨", "rail"},
            {"架", "frame"}, {"座", "base"}, {"盘", "disc"}, {"盖", "cover"},
            {"壳", "housing"}, {"箱", "box"}, {"柜", "cabinet"}, {"床", "bed"},
            {"梁", "beam"}, {"柱", "column"}, {"板", "plate"}, {"管", "pipe"},
            {"线", "wire"}, {"绳", "rope"}, {"带", "belt"}, {"链", "chain"},
            {"钩", "hook"}, {"爪", "jaw"}, {"钳", "clamp"}, {"夹", "gripper"},
            {"刀", "blade"}, {"锯", "saw"}, {"钻", "drill"}, {"锤", "hammer"},
            {"冲", "punch"}, {"模", "die"}, {"芯", "core"}, {"杆", "rod"},
            {"柄", "handle"}, {"环", "ring"}, {"垫", "pad"}, {"块", "block"},
            {"片", "sheet"}, {"层", "layer"}, {"段", "section"}, {"区", "zone"},
            {"槽", "groove"}, {"孔", "hole"}, {"缝", "seam"}, {"口", "port"},
            {"嘴", "nozzle"}, {"端", "end"}, {"面", "face"}, {"边", "edge"},
            {"角", "corner"}, {"点", "point"}, {"圈", "loop"}, {"网", "mesh"},
            {"筛", "screen"}, {"膜", "membrane"}, {"布", "cloth"}, {"纸", "paper"},
            {"丝", "wire"}, {"棒", "bar"}, {"坯", "billet"}, {"粉", "powder"},
            {"屑", "chip"}, {"渣", "slag"}, {"灰", "ash"}, {"烟", "smoke"},
            {"雾", "mist"}, {"汽", "vapor"}, {"脂", "grease"}, {"漆", "paint"},
            {"胶", "glue"}, {"力", "force"}, {"能", "energy"}, {"功", "work"},
            {"热", "heat"}, {"冷", "cold"}, {"湿", "moisture"}, {"干", "dry"},
            {"光", "light"}, {"色", "color"}, {"声", "sound"}, {"位", "position"},
            {"向", "direction"}, {"速", "velocity"}, {"时", "time"}, {"距", "distance"},
            {"高", "height"}, {"宽", "width"}, {"长", "length"}, {"深", "depth"},
            {"厚", "thickness"}, {"薄", "thin"}, {"轻", "lightweight"}, {"重", "heavy"},
            {"粗", "coarse"}, {"细", "fine"}, {"精", "precision"}, {"准", "accuracy"},
            {"密", "dense"}, {"疏", "sparse"}, {"强", "strong"}, {"弱", "weak"},
            {"硬", "hard"}, {"软", "soft"}, {"紧", "tight"}, {"松", "loose"},
            {"快", "fast"}, {"慢", "slow"}, {"多", "multi"}, {"少", "few"},
            {"正", "positive"}, {"反", "reverse"}, {"双", "dual"}, {"单", "single"},
            {"全", "full"}, {"半", "half"}, {"机械", "mechanical"}, {"机械臂", "mechanical_arm"},
            {"机械手", "manipulator"}, {"智能", "intelligent"}, {"智能装备", "intelligent_equipment"}, {"下料机", "unloader"},
            {"卸料", "discharge"}, {"自动上料", "auto_loading"}, {"自动下料", "auto_unloading"}, {"自动给料", "auto_feeding"},
            {"自动送料", "auto_feed"}, {"分料", "sorting"}, {"合料", "merging"}, {"整列", "aligning"},
            {"翻转", "flipping"}, {"旋转", "rotating"}, {"平移", "translating"}, {"升降", "lifting"},
            {"横移", "traversing"}, {"纵移", "longitudinal"}, {"抓取", "gripping"}, {"吸取", "suction"},
            {"夹取", "clamping"}, {"放置", "placing"}, {"搬运", "handling"}, {"转运", "transferring"},
            {"堆垛", "stacking"}, {"装箱", "boxing"}, {"封箱", "sealing"}, {"缠绕", "wrapping"},
            {"捆扎", "strapping"}, {"打包带", "strapping_band"}, {"缠绕膜", "stretch_film"}, {"箱体", "crate"},
            {"料箱", "bin"}, {"料盘", "tray"}, {"料斗", "hopper"}, {"料槽", "chute"},
            {"料道", "feeder_track"}, {"料架", "rack"}, {"振动盘", "vibratory_bowl"}, {"振动给料", "vibratory_feeding"},
            {"输送", "conveying"}, {"输送带", "conveyor_belt"}, {"输送链", "conveyor_chain"}, {"输送辊", "conveyor_roller"},
            {"传送", "transport"}, {"传送到", "transport_to"}, {"转台", "turntable"}, {"转盘", "rotary_table"},
            {"转鼓", "rotary_drum"}, {"分度", "indexing"}, {"分度盘", "indexing_table"}, {"分度器", "indexer"},
            {"定位销", "dowel_pin"}, {"定位块", "locating_block"}, {"导向", "guiding"}, {"导柱", "guide_pillar"},
            {"导套", "guide_bushing"}, {"滑块", "slider"}, {"滑轨", "slide_rail"}, {"滑台", "slide_table"},
            {"滑板", "slide_plate"}, {"滑道", "slide_way"}, {"直线", "linear"}, {"直线导轨", "linear_guide"},
            {"直线轴承", "linear_bearing"}, {"直线模组", "linear_module"}, {"直线电机模组", "linear_motor_module"}, {"油缸", "oil_cylinder"},
            {"液压缸", "hydraulic_cylinder"}, {"气爪", "pneumatic_gripper"}, {"吸盘", "suction_cup"}, {"真空吸盘", "vacuum_cup"},
            {"电磁吸盘", "magnetic_chuck"}, {"永磁吸盘", "permanent_magnetic_chuck"}, {"治具", "jig"}, {"检测", "inspection"},
            {"检验", "check"}, {"测试台", "test_bench"}, {"试验台", "test_stand"}, {"测试机", "tester"},
            {"检测机", "inspection_machine"}, {"视觉检测", "vision_inspection"}, {"机器视觉", "machine_vision"}, {"相机", "camera"},
            {"镜头", "lens"}, {"光源", "light_source"}, {"环形光源", "ring_light"}, {"背光源", "backlight"},
            {"同轴光源", "coaxial_light"}, {"条码", "barcode"}, {"二维码", "qr_code"}, {"扫码", "scanning"},
            {"扫码枪", "scanner"}, {"读码器", "barcode_reader"}, {"RFID", "rfid"}, {"读写器", "reader_writer"},
            {"天线", "antenna"}, {"指纹", "fingerprint"}, {"人脸识别", "face_recognition"}, {"安全围栏", "safety_fence"},
            {"防护罩", "safety_cover"}, {"防护门", "safety_gate"}, {"安全开关", "safety_switch"}, {"限位开关", "limit_switch"},
            {"接近开关", "proximity_sensor"}, {"光电开关", "photoelectric_sensor"}, {"光电传感器", "photoelectric_sensor"}, {"光纤传感器", "fiber_optic_sensor"},
            {"激光传感器", "laser_sensor"}, {"位移传感器", "displacement_sensor"}, {"力传感器", "force_sensor"}, {"力矩传感器", "torque_sensor"},
            {"称重传感器", "load_cell"}, {"编码器", "encoder"}, {"旋转编码器", "rotary_encoder"}, {"光栅尺", "linear_scale"},
            {"磁栅", "magnetic_scale"}, {"球栅", "ball_grid"}, {"容栅", "capacitive_grid"}, {"伺服驱动", "servo_drive"},
            {"伺服控制", "servo_control"}, {"步进驱动", "stepper_drive"}, {"变频", "variable_frequency"}, {"变频调速", "variable_speed"},
            {"人机界面", "hmi"}, {"工控机", "industrial_pc"}, {"嵌入式", "embedded"}, {"单片机", "mcu"},
            {"驱动器", "driver"}, {"端子", "terminal"}, {"接线端子", "terminal_block"}, {"接插件", "connector"},
            {"电线", "wire"}, {"拖链", "cable_chain"}, {"线槽", "cable_tray"}, {"线束", "wiring_harness"},
            {"航插", "aviation_plug"}, {"报警灯", "alarm_light"}, {"声光报警", "audible_visual_alarm"}, {"三色灯", "stack_light"},
            {"指示灯柱", "signal_tower"}, {"急停开关", "e_stop_switch"}, {"钥匙开关", "key_switch"}, {"选择开关", "selector_switch"},
            {"旋钮", "knob"}, {"电位器", "potentiometer"}, {"手轮", "handwheel"}, {"操作面板", "operator_panel"},
            {"控制面板", "control_panel"}, {"远程IO", "remote_io"}, {"分布式IO", "distributed_io"}, {"IO模块", "io_module"},
            {"通讯模块", "communication_module"}, {"网关", "gateway"}, {"交换机", "network_switch"}, {"路由器", "router"},
            {"串口服务器", "serial_server"}, {"协议转换", "protocol_converter"}, {"信号隔离器", "signal_isolator"}, {"安全栅", "safety_barrier"},
            {"浪涌保护", "surge_protection"}, {"防雷器", "lightning_arrester"}, {"散热", "cooling"}, {"散热器", "radiator"},
            {"散热风扇", "cooling_fan"}, {"风冷", "air_cooling"}, {"水冷", "water_cooling"}, {"油冷", "oil_cooling"},
            {"自然冷却", "natural_cooling"}, {"强制风冷", "forced_air_cooling"}, {"润滑脂", "grease"}, {"集中润滑", "centralized_lubrication"},
            {"自动润滑", "auto_lubrication"}, {"油雾润滑", "oil_mist_lubrication"}, {"油气润滑", "oil_air_lubrication"}, {"喷油润滑", "oil_spray_lubrication"},
            {"浸油润滑", "oil_bath_lubrication"}, {"液压站", "hydraulic_station"}, {"气压站", "pneumatic_station"}, {"液压系统", "hydraulic_system"},
            {"气动系统", "pneumatic_system"}, {"动力站", "power_unit"}, {"油源", "oil_source"}, {"气源", "air_source"},
            {"油箱", "oil_tank"}, {"气罐", "air_tank"}, {"蓄能器", "accumulator"}, {"滤芯", "filter_element"},
            {"滤网", "strainer"}, {"除尘过滤", "dust_filter"}, {"除油过滤", "oil_removal_filter"}, {"钢结构", "steel_structure"},
            {"机架", "machine_frame"}, {"底座", "base_frame"}, {"机座", "machine_base"}, {"机体", "machine_body"},
            {"面板", "panel"}, {"外壳", "enclosure"}, {"防护罩壳", "protective_cover"}, {"机箱", "chassis"},
            {"机柜", "enclosure_cabinet"}, {"控制柜", "control_cabinet"}, {"分线盒", "junction_box"}, {"接线盒", "terminal_box"},
            {"按钮盒", "button_box"},

            // ===== Expanded Vocabulary v2.0 =====

            {"无刷电机", "brushless_motor"},
            {"永磁电机", "permanent_magnet_motor"},
            {"调速电机", "variable_speed_motor"},
            {"双速电机", "two_speed_motor"},
            {"多速电机", "multi_speed_motor"},
            {"直驱电机", "direct_drive_motor"},
            {"电源模块", "power_module"},
            {"输入模块", "input_module"},
            {"输出模块", "output_module"},
            {"模拟量输入模块", "analog_input_module"},
            {"模拟量输出模块", "analog_output_module"},
            {"数字量输入模块", "digital_input_module"},
            {"数字量输出模块", "digital_output_module"},
            {"热电偶模块", "thermocouple_module"},
            {"热电阻模块", "rtd_module"},
            {"高速计数模块", "high_speed_counter_module"},
            {"位置模块", "position_module"},
            {"运动控制模块", "motion_control_module"},
            {"稳压器", "voltage_regulator"},
            {"蓄电池", "battery"},
            {"铅酸电池", "lead_acid_battery"},
            {"锂电池", "lithium_battery"},
            {"电池组", "battery_pack"},
            {"端子排", "terminal_strip"},
            {"接线排", "terminal_board"},
            {"电缆接头", "cable_gland"},
            {"滤波", "filtering"},
            {"滤波器", "filter_device"},
            {"EMC滤波器", "emc_filter"},
            {"电抗器", "reactor"},
            {"进线电抗器", "line_reactor"},
            {"出线电抗器", "load_reactor"},
            {"直流电抗器", "dc_reactor"},
            {"节流阀", "throttle_valve"},
            {"单向阀", "check_valve"},
            {"溢流阀", "relief_valve"},
            {"伺服阀", "servo_valve"},
            {"比例伺服阀", "proportional_servo_valve"},
            {"电液伺服阀", "electro_hydraulic_servo_valve"},
            {"换向阀", "directional_valve"},
            {"电磁换向阀", "solenoid_directional_valve"},
            {"手动换向阀", "manual_directional_valve"},
            {"液控单向阀", "pilot_check_valve"},
            {"顺序阀", "sequence_valve"},
            {"调速阀", "speed_control_valve"},
            {"分流阀", "flow_divider"},
            {"集流阀", "flow_combiner"},
            {"充液阀", "prefill_valve"},
            {"插装阀", "cartridge_valve"},
            {"逻辑阀", "logic_valve"},
            {"柱塞缸", "plunger_cylinder"},
            {"活塞缸", "piston_cylinder"},
            {"双作用缸", "double_acting_cylinder"},
            {"单作用缸", "single_acting_cylinder"},
            {"增压缸", "booster_cylinder"},
            {"步进驱动器", "stepper_driver"},
            {"变频器参数", "inverter_parameter"},
            {"变频器频率", "inverter_frequency"},
            {"载波频率", "carrier_frequency"},
            {"加减速时间", "accel_decel_time"},
            {"转矩提升", "torque_boost"},
            {"V/F控制", "vf_control"},
            {"矢量控制", "vector_control"},
            {"直接转矩控制", "direct_torque_control"},
            {"无传感器控制", "sensorless_control"},
            {"编码器反馈", "encoder_feedback"},
            {"电子齿轮", "electronic_gear"},
            {"电子凸轮", "electronic_cam"},
            {"总线通讯", "fieldbus_communication"},
            {"脉冲方向", "pulse_direction"},
            {"正负脉冲", "cw_ccw_pulse"},
            {"回零", "homing"},
            {"软限位", "soft_limit"},
            {"硬限位", "hard_limit"},
            {"扭矩限制", "torque_limit"},
            {"速度限制", "speed_limit"},
            {"位置环", "position_loop"},
            {"速度环", "speed_loop"},
            {"电流环", "current_loop"},
            {"陷波滤波器", "notch_filter"},
            {"低通滤波", "low_pass_filter"},
            {"惯量比", "inertia_ratio"},
            {"刚性", "stiffness"},
            {"增益", "gain"},
            {"积分增益", "integral_gain"},
            {"微分增益", "derivative_gain"},
            {"前馈增益", "feedforward_gain"},
            {"零漂", "zero_drift"},
            {"温漂", "temperature_drift"},
            {"死区补偿", "deadband_compensation"},
            {"摩擦补偿", "friction_compensation"},
            {"间隙补偿", "backlash_compensation"},
            {"磁力启动器", "magnetic_starter"},
            {"星三角启动", "star_delta_starter"},
            {"自耦变压器启动", "auto_transformer_starter"},
            {"频敏变阻器", "frequency_sensitive_rheostat"},
            {"行程开关", "travel_switch"},
            {"微动开关", "micro_switch"},
            {"浮球开关", "float_switch"},
            {"流量开关", "flow_switch"},
            {"压力开关", "pressure_switch"},
            {"温度开关", "temperature_switch"},
            {"液位开关", "level_switch"},
            {"通用继电器", "general_purpose_relay"},
            {"热继电器", "thermal_relay"},
            {"时间继电器", "time_relay"},
            {"中间继电器", "intermediate_relay"},
            {"固态继电器", "solid_state_relay"},
            {"电压继电器", "voltage_relay"},
            {"电流继电器", "current_relay"},
            {"断相保护", "phase_loss_protection"},
            {"过载保护", "overload_protection"},
            {"短路保护", "short_circuit_protection"},
            {"漏电保护", "leakage_protection"},
            {"过压保护", "overvoltage_protection"},
            {"欠压保护", "undervoltage_protection"},
            {"过流保护", "overcurrent_protection"},
            {"缺相保护", "phase_failure_protection"},
            {"逆相保护", "phase_reversal_protection"},
            {"死区", "deadband"},
            {"迟滞", "hysteresis"},
            {"超调量", "overshoot"},
            {"稳态误差", "steady_state_error"},
            {"上升时间", "rise_time"},
            {"响应时间", "response_time"},
            {"调节时间", "settling_time"},
            {"峰值时间", "peak_time"},
            {"控制周期", "control_cycle"},
            {"扫描周期", "scan_cycle"},
            {"任务周期", "task_period"},
            {"PID参数", "pid_parameter"},
            {"比例增益", "proportional_gain"},
            {"积分时间", "integral_time"},
            {"微分时间", "derivative_time"},
            {"比例带", "proportional_band"},
            {"控制作用", "control_action"},
            {"正作用", "direct_action"},
            {"反作用", "reverse_action"},
            {"比值控制", "ratio_control"},
            {"分程控制", "split_range_control"},
            {"超驰控制", "override_control"},
            {"选择控制", "selective_control"},
            {"顺控", "sequence_control"},
            {"批量控制", "batch_control"},
            {"信号调理器", "signal_conditioner"},
            {"温控器", "temperature_controller"},
            {"液位控制器", "level_controller"},
            {"流量控制器", "flow_controller"},
            {"压力控制器", "pressure_controller"},
            {"程序控制", "program_control"},
            {"手动模式", "manual_mode"},
            {"自动模式", "auto_mode"},
            {"远程模式", "remote_mode"},
            {"就地控制", "local_control"},
            {"无扰动切换", "bumpless_transfer"},
            {"抗积分饱和", "anti_windup"},
            {"输出限幅", "output_clamping"},
            {"速率限制", "rate_limiting"},
            {"滤波常数", "filter_constant"},
            {"采样时间", "sampling_time"},
            {"控制精度", "control_accuracy"},
            {"响应带宽", "response_bandwidth"},
            {"开环控制", "open_loop_control"},
            {"闭环控制", "closed_loop_control"},
            {"单回路控制", "single_loop_control"},
            {"多回路控制", "multi_loop_control"},
            {"复杂控制", "advanced_control"},
            {"先进控制", "apc"},
            {"模型预测控制", "mpc"},
            {"自适应控制", "adaptive_control"},
            {"模糊控制", "fuzzy_control"},
            {"神经网络控制", "neural_network_control"},
            {"专家控制", "expert_control"},
            {"鲁棒控制", "robust_control"},
            {"最优控制", "optimal_control"},
            {"推断控制", "inferential_control"},
            {"前馈补偿", "feedforward_compensation"},
            {"扰动抑制", "disturbance_rejection"},
            {"解耦控制", "decoupling_control"},
            {"手操器", "manual_station"},
            {"无纸记录仪", "paperless_recorder"},
            {"有纸记录仪", "chart_recorder"},
            {"数据记录仪", "data_logger"},
            {"回路整定", "loop_tuning"},
            {"阶跃响应", "step_response"},
            {"脉冲响应", "impulse_response"},
            {"频率响应", "frequency_response"},
            {"传递函数", "transfer_function"},
            {"一阶系统", "first_order_system"},
            {"二阶系统", "second_order_system"},
            {"滞后", "lag"},
            {"纯滞后", "dead_time"},
            {"时间常数", "time_constant"},
            {"过程模型", "process_model"},
            {"系统辨识", "system_identification"},
            {"热电偶", "thermocouple"},
            {"K型热电偶", "type_k_thermocouple"},
            {"T型热电偶", "type_t_thermocouple"},
            {"E型热电偶", "type_e_thermocouple"},
            {"热电阻", "rtd"},
            {"双金属温度计", "bimetal_thermometer"},
            {"压力变送器", "pressure_transmitter"},
            {"差压变送器", "differential_pressure_transmitter"},
            {"绝压变送器", "absolute_pressure_transmitter"},
            {"电磁流量计", "electromagnetic_flowmeter"},
            {"涡街流量计", "vortex_flowmeter"},
            {"超声波流量计", "ultrasonic_flowmeter"},
            {"质量流量计", "mass_flowmeter"},
            {"科氏流量计", "coriolis_flowmeter"},
            {"涡轮流量计", "turbine_flowmeter"},
            {"孔板流量计", "orifice_flowmeter"},
            {"雷达液位计", "radar_level_meter"},
            {"导波雷达", "guided_wave_radar"},
            {"超声波液位计", "ultrasonic_level_meter"},
            {"磁翻板液位计", "magnetic_level_gauge"},
            {"浮球液位计", "float_level_switch"},
            {"加速度传感器", "accelerometer"},
            {"振动传感器", "vibration_sensor"},
            {"视觉传感器", "vision_sensor"},
            {"色标传感器", "color_sensor"},
            {"温度传感器", "temperature_sensor"},
            {"压力传感器", "pressure_sensor"},
            {"流量传感器", "flow_sensor"},
            {"湿度传感器", "humidity_sensor"},
            {"气体检测器", "gas_detector"},
            {"烟感探测器", "smoke_detector"},
            {"火焰探测器", "flame_detector"},
            {"红外测温仪", "infrared_thermometer"},
            {"热成像仪", "thermal_camera"},
            {"示波器", "oscilloscope"},
            {"万用表", "multimeter"},
            {"钳形表", "clamp_meter"},
            {"兆欧表", "megger"},
            {"过程校验仪", "process_calibrator"},
            {"标准源", "standard_source"},
            {"拉伸试验机", "tensile_test_machine"},
            {"压缩试验机", "compression_tester"},
            {"弯曲试验机", "bend_tester"},
            {"工具显微镜", "toolmakers_microscope"},
            {"气密检测仪", "airtightness_tester"},
            {"差压检漏仪", "differential_pressure_leak_tester"},
            {"推拉力计", "force_gauge"},
            {"扭力计", "torque_gauge"},
            {"转速表", "tachometer"},
            {"频闪仪", "stroboscope"},
            {"风速仪", "anemometer"},
            {"声级计", "sound_level_meter"},
            {"照度计", "lux_meter"},
            {"温湿度计", "thermohygrometer"},
            {"露点仪", "dew_point_meter"},
            {"氧分析仪", "oxygen_analyzer"},
            {"气体分析仪", "gas_analyzer"},
            {"分光光度计", "spectrophotometer"},
            {"水份测定仪", "moisture_analyzer"},
            {"熔融指数仪", "melt_indexer"},
            {"量规", "gauge"},
            {"卡尺", "caliper"},
            {"千分尺", "micrometer"},
            {"百分表", "dial_indicator"},
            {"千分表", "dial_test_indicator"},
            {"塞尺", "feeler_gauge"},
            {"环规", "ring_gauge"},
            {"螺纹规", "thread_gauge"},
            {"以太网", "ethernet"},
            {"工业以太网", "industrial_ethernet"},
            {"防火墙", "firewall"},
            {"协议转换器", "protocol_converter"},
            {"环网", "ring_network"},
            {"星形网络", "star_network"},
            {"总线拓扑", "bus_topology"},
            {"冗余", "redundant"},
            {"双机热备", "hot_standby"},
            {"主从", "master_slave"},
            {"客户端", "client"},
            {"服务端", "server"},
            {"轮询", "polling"},
            {"事件驱动", "event_driven"},
            {"发布订阅", "pub_sub"},
            {"请求响应", "request_response"},
            {"广播", "broadcast"},
            {"组播", "multicast"},
            {"单播", "unicast"},
            {"标签", "tag_id"},
            {"数据块", "data_block"},
            {"字节偏移", "byte_offset"},
            {"位偏移", "bit_offset"},
            {"命名空间", "namespace"},
            {"节点", "node"},
            {"地址空间", "address_space"},
            {"连接超时", "connection_timeout"},
            {"重连", "reconnect"},
            {"心跳", "heartbeat"},
            {"看门狗", "watchdog"},
            {"数据订阅", "data_subscription"},
            {"批量读取", "batch_read"},
            {"QoS", "qos"},
            {"TLS", "tls"},
            {"VPN", "vpn"},
            {"NAT", "nat"},
            {"DHCP", "dhcp"},
            {"DNS", "dns"},
            {"IP地址", "ip_address"},
            {"MAC地址", "mac_address"},
            {"子网掩码", "subnet_mask"},
            {"默认网关", "default_gateway"},
            {"接口", "interface"},
            {"网卡", "nic"},
            {"光纤收发器", "media_converter"},
            {"光电转换器", "fiber_transceiver"},
            {"SFP", "sfp"},
            {"网线", "ethernet_cable"},
            {"光纤", "fiber_optic"},
            {"单模", "single_mode"},
            {"多模", "multi_mode"},
            {"网桥", "bridge"},
            {"中继器", "repeater"},
            {"集线器", "hub"},
            {"无线AP", "wireless_ap"},
            {"无线网桥", "wireless_bridge"},
            {"4G路由器", "4g_router"},
            {"5G路由器", "5g_router"},
            {"北斗", "beidou"},
            {"GPS", "gps"},
            {"NTP", "ntp"},
            {"不良率", "defect_rate"},
            {"返工率", "rework_rate"},
            {"直通率", "first_pass_yield"},
            {"设备利用率", "utilization"},
            {"产能", "capacity"},
            {"节拍", "takt_time"},
            {"节拍时间", "takt_time"},
            {"中心线", "center_line"},
            {"控制上限", "ucl"},
            {"控制下限", "lcl"},
            {"规格上限", "usl"},
            {"规格下限", "lsl"},
            {"CPK", "cpk"},
            {"标准偏差", "standard_deviation"},
            {"测量系统分析", "msa"},
            {"检定", "verification"},
            {"溯源", "traceability"},
            {"统计过程控制", "spc"},
            {"控制图", "control_chart"},
            {"过程能力", "process_capability"},
            {"抽样", "sampling"},
            {"全检", "full_inspection"},
            {"抽检", "random_inspection"},
            {"免检", "skip_inspection"},
            {"来料检验", "iqc"},
            {"过程检验", "ipqc"},
            {"成品检验", "oqc"},
            {"出货检验", "outgoing_inspection"},
            {"首件检验", "first_piece_inspection"},
            {"末件检验", "last_piece_inspection"},
            {"质量成本", "cost_of_quality"},
            {"预防成本", "prevention_cost"},
            {"鉴定成本", "appraisal_cost"},
            {"内部损失", "internal_failure_cost"},
            {"外部损失", "external_failure_cost"},
            {"纠正措施", "corrective_action"},
            {"预防措施", "preventive_action"},
            {"8D报告", "eight_d_report"},
            {"鱼骨图", "fishbone_diagram"},
            {"柏拉图", "pareto_chart"},
            {"直方图", "histogram"},
            {"散点图", "scatter_plot"},
            {"FMEA", "fmea"},
            {"PFMEA", "pfmea"},
            {"DFMEA", "dfmea"},
            {"控制计划", "control_plan"},
            {"作业指导书", "sop"},
            {"标准作业", "standard_work"},
            {"看板", "kanban"},
            {"安灯", "andon"},
            {"价值流图", "vsm"},
            {"快速换模", "smed"},
            {"全面生产维护", "tpm"},
            {"5S", "five_s"},
            {"精益生产", "lean_manufacturing"},
            {"六西格玛", "six_sigma"},
            {"PPAP", "ppap"},
            {"APQP", "apqp"},
            {"电度", "kilowatt_hour"},
            {"峰谷平", "peak_valley_flat"},
            {"峰时", "peak_hours"},
            {"谷时", "off_peak_hours"},
            {"平时", "standard_hours"},
            {"碳排放", "carbon_emission"},
            {"碳足迹", "carbon_footprint"},
            {"排放浓度", "emission_concentration"},
            {"排放总量", "total_emission"},
            {"脱硝", "denitrification"},
            {"环保", "environmental"},
            {"在线监测", "online_monitoring"},
            {"数据采集仪", "data_logger"},
            {"数采仪", "dau"},
            {"能耗监测", "energy_monitoring"},
            {"节能", "energy_saving"},
            {"能效", "energy_efficiency"},
            {"单位能耗", "specific_energy_consumption"},
            {"综合能耗", "total_energy_consumption"},
            {"标煤", "coal_equivalent"},
            {"新能源", "renewable_energy"},
            {"光伏发电", "pv_generation"},
            {"风力发电", "wind_generation"},
            {"生物质能", "biomass_energy"},
            {"地热能", "geothermal_energy"},
            {"氢能", "hydrogen_energy"},
            {"余热回收", "waste_heat_recovery"},
            {"热电联产", "chp"},
            {"合同能源管理", "emc"},
            {"碳交易", "carbon_trading"},
            {"碳中和", "carbon_neutrality"},
            {"碳达峰", "carbon_peak"},
            {"排污许可证", "discharge_permit"},
            {"环境影响评价", "eia"},
            {"清洁生产", "clean_production"},
            {"循环经济", "circular_economy"},
            {"绿色工厂", "green_factory"},
            {"零排放", "zero_discharge"},
            {"中水回用", "reclaimed_water_reuse"},
            {"雨污分流", "storm_sewage_separation"},
            {"安全等级", "safety_level"},
            {"SIL", "sil"},
            {"SIL1", "sil1"},
            {"SIL2", "sil2"},
            {"SIL3", "sil3"},
            {"SIL4", "sil4"},
            {"防爆", "explosion_proof"},
            {"本安", "intrinsic_safety"},
            {"隔爆", "flameproof"},
            {"正压防爆", "pressurized_enclosure"},
            {"增安", "increased_safety"},
            {"防护等级", "ip_rating"},
            {"防雷", "lightning_protection"},
            {"静电防护", "esd_protection"},
            {"PPE", "ppe"},
            {"危险区域", "hazardous_area"},
            {"风险评估", "risk_assessment"},
            {"HAZOP", "hazop"},
            {"变更管理", "moc"},
            {"作业许可", "work_permit"},
            {"上锁挂牌", "loto"},
            {"应急预案", "emergency_plan"},
            {"事故", "incident"},
            {"未遂事件", "near_miss"},
            {"职业健康", "occupational_health"},
            {"安全标准化", "safety_standardization"},
            {"双重预防", "dual_prevention"},
            {"安全培训", "safety_training"},
            {"安全监护", "safety_supervision"},
            {"动火作业", "hot_work"},
            {"高处作业", "work_at_height"},
            {"受限空间", "confined_space"},
            {"临时用电", "temporary_power"},
            {"吊装作业", "lifting_operation"},
            {"盲板抽堵", "blinding"},
            {"断路作业", "road_blocking"},
            {"动土作业", "excavation_work"},
            {"中毒", "poisoning"},
            {"窒息", "asphyxiation"},
            {"灼伤", "burn"},
            {"触电", "electric_shock"},
            {"机械伤害", "mechanical_injury"},
            {"高处坠落", "fall_from_height"},
            {"物体打击", "struck_by_object"},
            {"火灾", "fire"},
            {"爆炸", "explosion"},
            {"泄漏", "leak"},
            {"隐患", "hazard"},
            {"隐患整改", "hazard_rectification"},
            {"安全投入", "safety_investment"},
            {"安全仪表系统", "sis"},
            {"紧急停车系统", "esd_system"},
            {"火气系统", "fgs"},
            {"可燃气体报警", "combustible_gas_alarm"},
            {"有毒气体报警", "toxic_gas_alarm"},
            {"消防泵", "fire_pump"},
            {"消火栓", "fire_hydrant"},
            {"灭火器", "fire_extinguisher"},
            {"喷淋系统", "sprinkler_system"},
            {"泡沫灭火", "foam_extinguishing"},
            {"气体灭火", "gas_extinguishing"},
            {"消防控制室", "fire_control_room"},
            {"冷冻水", "chilled_water"},
            {"冷却水", "cooling_water"},
            {"热水", "hot_water"},
            {"凝结水", "condensate"},
            {"新风系统", "fresh_air"},
            {"排风系统", "exhaust_air"},
            {"风量", "air_volume"},
            {"送风", "supply_air"},
            {"回风", "return_air"},
            {"除湿", "dehumidification"},
            {"加湿", "humidification"},
            {"FFU", "ffu"},
            {"高效过滤器", "hepa_filter"},
            {"中效过滤器", "medium_filter"},
            {"初效过滤器", "pre_filter"},
            {"温控阀", "temperature_control_valve"},
            {"电动调节阀", "electric_control_valve"},
            {"平衡阀", "balancing_valve"},
            {"分水器", "water_distributor"},
            {"集水器", "water_collector"},
            {"膨胀罐", "expansion_tank"},
            {"壳管换热器", "shell_tube_exchanger"},
            {"容积式换热器", "storage_water_heater"},
            {"蒸汽锅炉", "steam_boiler"},
            {"热水锅炉", "hot_water_boiler"},
            {"导热油炉", "thermal_oil_heater"},
            {"软水器", "water_softener"},
            {"除氧器", "deaerator"},

            // 工业以太网协议
            {"EtherNet/IP", "ethernet_ip"}, {"IEC104", "iec104"}, {"CIP协议", "cip"}, {"GSD文件", "gsd_file"}, {"GSDML", "gsdml"},
            {"EDS文件", "eds_file"}, {"RT实时", "rt_realtime"}, {"IRT等时", "irt_isochronous"},
            {"非周期性", "acyclic"}, {"周期性", "cyclic"}, {"组态", "configuration"},
            {"拓扑", "topology"}, {"设备描述", "device_description"}, {"信息体", "information_object"},
            {"传送原因", "cause_of_transmission"}, {"类型标识", "type_identifier"},
            {"总召唤", "general_interrogation"}, {"时钟同步", "clock_sync"}, {"时标", "time_tag"},
            // 日本PLC协议
            {"三菱", "mitsubishi"}, {"欧姆龙", "omron"}, {"基恩士", "keyence"},
            {"MELSEC", "melsec"}, {"MC协议", "mc_protocol"}, {"FINS协议", "fins_protocol"},
            {"HostLink", "hostlink"}, {"上位链接", "hostlink"}, {"KV系列", "kv_series"},
            {"FX系列", "fx_series"}, {"Q系列", "q_series"}, {"R系列", "r_series"},

            // 电力自动化协议
            {"IEC61850", "iec61850"}, {"MMS", "mms"}, {"Goose", "goose"},
            {"DNP3", "dnp3"}, {"电力自动化", "power_automation"},

            // 楼宇自动化协议
            {"KNX", "knx"}, {"KNXnet", "knxnet"}, {"楼宇自动化", "building_automation"},
            
            // 半导体/电子制造协议
            {"SECS", "secs"}, {"GEM", "gem"}, {"HSMS", "hsms"},

            // 数控系统协议
            {"Fanuc", "fanuc"}, {"Focas", "focas"}, {"海德汉", "heidenhain"},
            {"Heidenhain", "heidenhain"}, {"iTNC", "itnc"},

            // 工业物联网协议
            {"MTConnect", "mtconnect"}, {"Sparkplug", "sparkplug"}, {"SparkplugB", "sparkplugb"},
            {"OPC UA", "opc_ua"}, {"OPC UA PubSub", "opcua_pubsub"},
            {"Broker", "broker"},

            // 15 new protocol terms (v2.1.0)
            {"CODESYS", "codesys"}, {"Beckhoff", "beckhoff"}, {"ADS", "ads"},
            {"CC-Link", "cclink"}, {"PROFIBUS", "profibus"},
            {"Mitsubishi", "mitsubishi"}, {"FX", "fx"}, {"Panasonic", "panasonic"},
            {"Mewtocol", "mewtocol"}, {"Haas", "haas"}, {"CNC", "cnc"},
            {"840D", "840d"}, {"Siemens", "siemens"}, {"Mazak", "mazak"},
            {"DALI", "dali"}, {"M-Bus", "mbus"}, {"DLMS", "dlms"},
            {"COSEM", "cosem"}, {"HART", "hart"}, {"HART-IP", "hart_ip"},
            {"OPC DA", "opc_da"},
        };

        /// <summary>
        /// Translate a Chinese industrial term to English.
        /// Falls back to compound decomposition if no exact match.
        /// </summary>
        public static string Translate(string chinese)
        {
            if (string.IsNullOrEmpty(chinese)) return "";
            if (Map.TryGetValue(chinese, out string english)) return english;
            // Fallback: try compound decomposition
            return TranslateCompound(chinese);
        }

        /// <summary>
        /// Translate a Chinese string by decomposing unknown compounds into known vocabulary words.
        /// Uses greedy left-to-right longest-prefix matching against the vocabulary dictionary.
        /// Unknown segments are left as-is (will be converted to pinyin-like or stripped by Slugify).
        /// </summary>
        public static string TranslateCompound(string chinese)
        {
            if (string.IsNullOrEmpty(chinese)) return "";

            // Try exact match first (fast path)
            if (Map.TryGetValue(chinese, out string exact)) return exact;

            // Greedy left-to-right segmentation
            var result = new System.Text.StringBuilder();
            int i = 0;
            while (i < chinese.Length)
            {
                bool found = false;
                // Try longest match first (max 6 chars, typical Chinese compound)
                for (int len = Math.Min(6, chinese.Length - i); len >= 1; len--)
                {
                    string token = chinese.Substring(i, len);
                    if (Map.TryGetValue(token, out string english))
                    {
                        if (result.Length > 0) result.Append('_');
                        result.Append(english);
                        i += len;
                        found = true;
                        break;
                    }
                }
                if (!found)
                {
                    // Single unknown character try to keep digits/letters, skip others
                    char c = chinese[i];
                    if (char.IsLetterOrDigit(c))
                    {
                        if (result.Length > 0) result.Append('_');
                        result.Append(c);
                    }
                    i++;
                }
            }
            return result.ToString();
        }
        
        // Alias: direct dictionary access
        public static bool TryGet(string key, out string value) => Map.TryGetValue(key, out value);
    }
}
